package elemental.hunter

import io.mockk.*
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.util.*

/**
 * Server-side scaffolding tests for Elemental Hunter feature.
 * Generated by: agent_qc from REQ/DESIGN.
 * Date: 2026-03-19 06:17 UTC
 * TODO: Fill in assertions with actual implementation.
 */
class ElementalHunterServerTest {

    // Mock dependencies
    private lateinit var gameState: GameState
    private lateinit var player1: PlayerState
    private lateinit var player2: PlayerState
    private lateinit var token1: TokenState
    private lateinit var token2: TokenState

    @BeforeEach
    fun setup() {
        // Initialize a minimal game state for testing
        gameState = GameState(
            matchId = "test-match",
            level = 3,
            maxRounds = 15,
            currentRound = 1,
            currentTurn = "P1",
            players = mutableMapOf(),
            tokens = mutableListOf(),
            board = createTestBoard(),
            winner = null,
            matchStartTime = System.currentTimeMillis()
        )
        player1 = PlayerState(
            playerId = "P1",
            hp = 1000,
            mag = 0,
            elementAffinity = "Fire",
            elementQueue = mutableListOf("Fire"), // start with affinity element
            tileGainMultiplier = 1,
            doubleRollCooldown = 0,
            consecutiveRollsThisTurn = 0,
            ultimateExtraRolls = 0,
            emptyTileVisits = 0,
            comboCount = 0
        )
        player2 = PlayerState(
            playerId = "P2",
            hp = 1000,
            mag = 0,
            elementAffinity = "Ice",
            elementQueue = mutableListOf("Ice"),
            tileGainMultiplier = 1,
            doubleRollCooldown = 0,
            consecutiveRollsThisTurn = 0,
            ultimateExtraRolls = 0,
            emptyTileVisits = 0,
            comboCount = 0
        )
        gameState.players["P1"] = player1
        gameState.players["P2"] = player2

        token1 = TokenState(id = "P1-T1", owner = "P1", position = 51, atk = 0, frozenRounds = 0)
        token2 = TokenState(id = "P2-T1", owner = "P2", position = 0, atk = 0, frozenRounds = 0)
        gameState.tokens.add(token1)
        gameState.tokens.add(token2)
    }

    @Test
    fun `should roll dice and update state`() = runTest {
        // Given
        val diceRoll = 7 // not double

        // When
        val result = gameState.rollDice("P1", diceRoll)

        // Then
        assertTrue(result is RollResult.Success)
        assertEquals(1, player1.consecutiveRollsThisTurn)
        assertFalse(result.isDouble)
        assertNull(result.extraTurnGranted)
    }

    @Test
    fun `should grant extra turn on double roll when not in cooldown and below cap`() = runTest {
        // Given
        player1.consecutiveRollsThisTurn = 1 // below MAX=3
        player1.doubleRollCooldown = 0

        // When
        val result = gameState.rollDice("P1", dice = 6, isDouble = true)

        // Then
        assertTrue(result is RollResult.Success)
        assertTrue((result as RollResult.Success).extraTurnGranted)
        assertEquals(2, player1.consecutiveRollsThisTurn)
    }

    @Test
    fun `should not grant extra turn on double during cooldown`() = runTest {
        // Given
        player1.doubleRollCooldown = 1 // still in cooldown

        // When
        val result = gameState.rollDice("P1", dice = 6, isDouble = true)

        // Then
        assertTrue(result is RollResult.Success)
        assertFalse((result as RollResult.Success).extraTurnGranted)
    }

    @Test
    fun `should not grant extra turn when consecutive roll cap reached`() = runTest {
        // Given
        player1.consecutiveRollsThisTurn = 3 // MAX reached

        // When
        val result = gameState.rollDice("P1", dice = 6, isDouble = true)

        // Then
        assertTrue(result is RollResult.Success)
        assertFalse((result as RollResult.Success).extraTurnGranted)
    }

    @Test
    fun `should accumulate MAG when landing on non-affinity element`() = runTest {
        // Given: token1 on Ice tile (affinity=Fire)
        val iceTile = gameState.board.first { it is ElementalTile && it.element == "Ice" }
        token1.position = iceTile.id

        // When
        gameState.processLanding(token1, iceTile)

        // Then
        assertEquals(10 /* character.mag */, player1.mag)
    }

    @Test
    fun `should increase ATK when landing on affinity element`() = runTest {
        // Given: token1 on Fire tile (affinity=Fire)
        val fireTile = gameState.board.first { it is ElementalTile && it.element == "Fire" }
        token1.position = fireTile.id

        // When
        gameState.processLanding(token1, fireTile)

        // Then
        assertEquals(30 /* character.atk */, token1.atk)
    }

    @Test
    fun `should activate C3 combo when three identical elements consecutive`() = runTest {
        // Given queue is [Fire, Fire, ?], add Fire to trigger C3
        player1.elementQueue.clear()
        player1.elementQueue.addAll(listOf("Fire", "Fire", "Ice"))

        // When
        gameState.addElementToQueue("P1", "Fire")

        // Then
        // Queue should have removed those 3 Fires and applied Tier1 bonus (+150 ATK to all tokens)
        assertFalse(player1.elementQueue.contains("Fire")) // at least those 3 removed
        // Verify ATK bonus applied to tokens
        token1.atk shouldBeGreaterThan 0 // actual value depends on timing; after bonus increase
    }

    @Test
    fun `should perform kick when landing on enemy token not on Safe Zone`() = runTest {
        // Given: token2 at position that is not Safe Zone, token1 moves onto it
        val normalTile = gameState.board.first { it !is SafeZone && it !is FinalGoal }
        token2.position = normalTile.id
        token1.atk = 50

        // When
        gameState.processLanding(token1, normalTile)

        // Then
        assertEquals(950, player2.hp) // -50
        // token2 should be moved to nearest Safe Zone behind
        val safeZone = gameState.board.first { it is SafeZone }
        assertEquals(safeZone.id, token2.position)
        assertEquals(1, player1.kickCount)
    }

    @Test
    fun `should not kick if landing on Safe Zone`() = runTest {
        // Given: token2 on Safe Zone
        val safeTile = gameState.board.first { it is SafeZone }
        token2.position = safeTile.id
        token1.atk = 50

        // When
        gameState.processLanding(token1, safeTile)

        // Then
        assertEquals(1000, player2.hp) // unchanged
        assertEquals(safeTile.id, token2.position) // still there
    }

    @Test
    fun `should handle Final Goal: add element, attack opponent, return to Safe Zone`() = runTest {
        // Given: token1 reaches Final Goal (P1 FinalGoal is 31)
        val finalGoal = gameState.board.first { it is FinalGoal && it.owner == "P1" }
        token1.position = finalGoal.id
        token1.atk = 100
        player1.elementQueue.clear()

        // When
        gameState.processFinalGoal(token1, finalGoal)

        // Then
        // Player chooses element to add (usually Affinity? Server should provide choices)
        assertEquals(1, player1.elementQueue.size)
        // Opponent HP reduced by token ATK
        assertEquals(900, player2.hp)
        // Token returned to Safe Zone of player
        val startSafe = gameState.board.first { it is SafeZone && it.owner == "P1" }
        assertEquals(startSafe.id, token1.position)
    }

    @Test
    fun `should trigger win by KO when HP <= 0`() = runTest {
        // Given
        player2.hp = 50
        token1.atk = 100

        // When
        val result = gameState.applyKick(attacker = token1, defender = token2)

        // Then
        assertTrue(result.koOccurred)
        assertEquals("P1", gameState.winner)
    }

    @Test
    fun `should handle Artifact Swap with insufficient queue (no-op)`() = runTest {
        // Given: queue has only 1 element
        player1.elementQueue.clear()
        player1.elementQueue.add("Fire")
        player1.emptyTileVisits = 1 // Swap unlocked

        // When
        gameState.applyArtifact("P1", "Swap")

        // Then
        // Queue unchanged, artifact consumed? Spec: "artifact bỏ qua" — no effect, maybe still consume? Assume not consume.
        assertEquals(1, player1.elementQueue.size)
        assertEquals("Fire", player1.elementQueue[0])
    }

    @Test
    fun `should add affinity element on Charge artifact`() = runTest {
        // Given
        player1.elementAffinity = "Fire"
        player1.emptyTileVisits = 3 // Charge unlocked

        // When
        gameState.applyArtifact("P1", "Charge")

        // Then
        assertEquals("Fire", player1.elementQueue.last())
    }

    @Test
    fun `should reduce MAG by 50 when using Ultimate Extra Roll and grant extra turn`() = runTest {
        // Given
        player1.mag = 60
        player1.consecutiveRollsThisTurn = 1 // still room for extra

        // When
        val used = gameState.useUltimate("P1")

        // Then
        assertTrue(used)
        assertEquals(10, player1.mag)
        assertEquals(1, player1.ultimateExtraRolls)
    }

    @Test
    fun `should not allow Ultimate when below MAG threshold`() = runTest {
        // Given
        player1.mag = 30

        // When
        val used = gameState.useUltimate("P1")

        // Then
        assertFalse(used)
    }

    @Test
    fun `should decrease double roll cooldown each round`() = runTest {
        // Given
        player1.doubleRollCooldown = 2

        // When
        gameState.startNewRound()

        // Then
        assertEquals(1, player1.doubleRollCooldown)
    }

    @Test
    fun `should reset consecutive rolls on turn switch`() = runTest {
        // Given
        player1.consecutiveRollsThisTurn = 3

        // When
        gameState.switchTurn()

        // Then
        assertEquals(0, player1.consecutiveRollsThisTurn)
        // Now currentTurn should be P2
        assertEquals("P2", gameState.currentTurn)
    }
}

// --- Mock helper data classes (simplified) ---
private fun createTestBoard(): List<TileState> {
    // Create 61-tile board with necessary types
    val tiles = mutableListOf<TileState>()
    // Safe Zones: Start tiles (51 for P1, 0 for P2) and maybe others
    tiles.add(SafeZone(id = 0, owner = "P2"))
    tiles.add(SafeZone(id = 51, owner = "P1"))
    // Add some Elemental Tiles
    listOf("Fire", "Ice", "Grass", "Rock").forEach { element ->
        repeat(10) { index ->
            tiles.add(ElementalTile(id = tiles.size, element = element))
        }
    }
    // Add some empty tiles
    repeat(10) { tiles.add(EmptyTile(id = tiles.size)) }
    // Add Final Goal tiles
    tiles.add(FinalGoal(id = 31, owner = "P1"))
    tiles.add(FinalGoal(id = 25, owner = "P2"))
    // Fill rest with Normal Tiles
    while (tiles.size < 61) {
        tiles.add(NormalTile(id = tiles.size))
    }
    return tiles
}

// Simulated state classes (would be actual implementations)
open class TileState(val id: Int)
class SafeZone(id: Int, val owner: String) : TileState(id)
class FinalGoal(id: Int, val owner: String) : TileState(id)
class ElementalTile(id: Int, val element: String) : TileState(id)
class EmptyTile(id: Int) : TileState(id)
class NormalTile(id: Int) : TileState(id)

data class TokenState(
    val id: String,
    val owner: String,
    var position: Int,
    var atk: Int,
    var frozenRounds: Int
)

data class PlayerState(
    val playerId: String,
    var hp: Int,
    var mag: Int,
    val elementAffinity: String,
    val elementQueue: MutableList<String>,
    var tileGainMultiplier: Int,
    var doubleRollCooldown: Int,
    var consecutiveRollsThisTurn: Int,
    var ultimateExtraRolls: Int,
    var emptyTileVisits: Int,
    var comboCount: Int,
    var kickCount: Int = 0
) {
    val magCap = 100 // placeholder
}

data class GameState(
    val matchId: String,
    var level: Int,
    val maxRounds: Int,
    var currentRound: Int,
    var currentTurn: String,
    val players: MutableMap<String, PlayerState>,
    val tokens: MutableList<TokenState>,
    val board: List<TileState>,
    var winner: String?,
    var matchStartTime: Long,
    var matchEndTime: Long? = null
) {
    // Methods to be implemented; signatures for test compilation
    fun rollDice(playerId: String, dice: Int, isDouble: Boolean = false): RollResult {
        val player = players[playerId] ?: return RollResult.InvalidPlayer
        player.consecutiveRollsThisTurn++
        var extraTurn = false
        if (isDouble && player.consecutiveRollsThisTurn < 3 && player.doubleRollCooldown == 0) {
            extraTurn = true
        }
        return RollResult.Success(isDouble, extraTurn)
    }

    fun processLanding(token: TokenState, tile: TileState) {
        // simplified
        when (tile) {
            is ElementalTile -> handleElementalTile(token, tile)
            is EmptyTile -> { /* trigger artifact */ }
            is FinalGoal -> processFinalGoal(token, tile)
            else -> {
                // Check for kick
                val enemy = tokens.find { it.owner != token.owner && it.position == tile.id && tile !is SafeZone }
                if (enemy != null) performKick(attacker = token, defender = enemy)
            }
        }
    }

    private fun handleElementalTile(token: TokenState, tile: ElementalTile) {
        val player = players[token.owner]!!
        if (tile.element == player.elementAffinity) {
            token.atk += 30 // character.atk
        } else {
            player.mag += 10
            player.elementQueue.add(tile.element)
            if (player.elementQueue.size > player.magCap) { // placeholder for maxElementQueue
                player.elementQueue.removeAt(0)
            }
        }
    }

    private fun performKick(attacker: TokenState, defender: TokenState) {
        val attackerOwner = players[attacker.owner]!!
        val defenderOwner = players[defender.owner]!!
        defenderOwner.hp -= attacker.atk
        // Find nearest safe zone behind defender
        val safe = board.first { it is SafeZone && (it as SafeZone).owner == defender.owner }
        defender.position = safe.id
        attackerOwner.kickCount++
    }

    fun processFinalGoal(token: TokenState, goal: FinalGoal) {
        val player = players[token.owner]!!
        // Choose element to add: e.g., affinity
        player.elementQueue.add(player.elementAffinity)
        // Attack opponent
        val opponent = players.values.first { it.playerId != player.playerId }
        opponent.hp -= token.atk
        // Return token to safe zone
        val safe = board.first { it is SafeZone && (it as SafeZone).owner == player.playerId }
        token.position = safe.id
    }

    fun addElementToQueue(playerId: String, element: String) {
        val player = players[playerId]!!
        player.elementQueue.add(element)
        // Check combo (simplified)
        if (player.elementQueue.size >= 3) {
            val lastThree = player.elementQueue.takeLast(3)
            if (lastThree.distinct().size == 1) {
                // C3 combo
                repeat(3) { player.elementQueue.removeLast() }
                tokenForPlayer(playerId)?.atk = (tokenForPlayer(playerId)?.atk ?: 0) + 150
                player.comboCount++
            }
        }
    }

    private fun tokenForPlayer(playerId: String) = tokens.firstOrNull { it.owner == playerId }

    fun applyArtifact(playerId: String, artifact: String) {
        val player = players[playerId]!!
        when (artifact) {
            "Swap" -> if (player.elementQueue.size >= 2) {
                // Swap adjacent
                Collections.swap(player.elementQueue, 0, 1)
            }
            "Change" -> {
                if (player.elementQueue.isNotEmpty()) {
                    player.elementQueue[0] = listOf("Fire","Ice","Grass","Rock").first { it != player.elementQueue[0] }
                }
            }
            "Charge" -> player.elementQueue.add(player.elementAffinity)
        }
    }

    fun useUltimate(playerId: String): Boolean {
        val player = players[playerId]!!
        if (player.mag >= 50 && player.consecutiveRollsThisTurn < 3) {
            player.mag -= 50
            player.ultimateExtraRolls++
            return true
        }
        return false
    }

    fun startNewRound() {
        players.values.forEach { it.doubleRollCooldown = maxOf(0, it.doubleRollCooldown - 1) }
    }

    fun switchTurn() {
        currentTurn = if (currentTurn == "P1") "P2" else "P1"
        players[currentTurn]?.consecutiveRollsThisTurn = 0
    }

    fun applyKick(attacker: TokenState, defender: TokenState): KickResult {
        val attackerOwner = players[attacker.owner]!!
        val defenderOwner = players[defender.owner]!!
        defenderOwner.hp -= attacker.atk
        val safe = board.first { it is SafeZone && (it as SafeZone).owner == defender.owner }
        defender.position = safe.id
        attackerOwner.kickCount++
        if (defenderOwner.hp <= 0) {
            winner = attacker.owner
            return KickResult.KO(attacker.owner)
        }
        return KickResult.Success
    }
}

sealed class RollResult {
    data class Success(val isDouble: Boolean, val extraTurnGranted: Boolean?) : RollResult()
    object InvalidPlayer : RollResult()
}
sealed class KickResult {
    object Success : KickResult()
    data class KO(val winner: String) : KickResult()
}

// Assertion helper
infix fun Int.shouldBeGreaterThan(expected: Int): Unit = assertTrue(this > expected)
