// src/tests/server/elemental-hunter.test.kt
// Generated by: agent_qc from analysis/REQ-elemental-hunter.md & DESIGN-elemental-hunter.md
// Date: 2026-03-19 10:55 UTC
// Language: Kotlin with JUnit5 (Jupiter)

package elemental_hunter

import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import kotlin.test.assertNotNull
import kotlin.test.assertFalse
import kotlin.test.assertTrue

// --- Mock Imports (replace with real when available) ---
// Assume these classes exist in server implementation:
// - GameState, PlayerState, TokenState, TileState
// - ElementEngine, CombatEngine, TurnHandler, ArtifactHandler
// We will use simplified test doubles.

// --- Helper Functions (for deterministic tests) ---
fun fakeDiceSum(vararg values: Int): Int = values.sum()

// --- Core Mechanics Tests ---

class ElementalHunterServerTests {

    @Test
    fun `should roll dice sum between 2 and 12`() {
        // Simulate RNG via seeded random; here just check ranges
        val dice1 = 4
        val dice2 = 5
        val sum = dice1 + dice2
        assertTrue(sum in 2..12)
    }

    @Test
    fun `double roll should grant extra turn when cooldown inactive and cap not reached`() {
        val state = createTestGameState()
        state.currentPlayer.doubleRollCooldown = 0
        state.currentPlayer.consecutiveRollsThisTurn = 1 // less than MAX=3
        val dice = Pair(6,6)
        val isDouble = dice.first == dice.second
        if (isDouble && state.currentPlayer.consecutiveRollsThisTurn < 3 && state.currentPlayer.doubleRollCooldown == 0) {
            state.extraRollsGranted++
        }
        assertEquals(1, state.extraRollsGranted)
    }

    @Test
    fun `double roll during cooldown should not grant extra turn`() {
        val state = createTestGameState()
        state.currentPlayer.doubleRollCooldown = 2 // active cooldown
        val dice = Pair(6,6)
        if (state.currentPlayer.doubleRollCooldown > 0) {
            // do nothing
        } else if (dice.first == dice.second) {
            state.extraRollsGranted++
        }
        assertEquals(0, state.extraRollsGranted)
    }

    @Test
    fun `consecutive roll cap reached should block extra turn from double and ultimate`() {
        val state = createTestGameState()
        state.currentPlayer.consecutiveRollsThisTurn = 3 // reached MAX=3
        val dice = Pair(5,5)
        if (state.currentPlayer.consecutiveRollsThisTurn < 3 && dice.first == dice.second) {
            state.extraRollsGranted++
        }
        assertEquals(0, state.extraRollsGranted)
    }

    @Test
    fun `element collection with affinity should increase token ATK`() {
        val player = createTestPlayer(affinity = ElementType.FIRE)
        val token = TokenState(owner = player.id, atk = 0)
        // Simulate landing on Fire elemental tile
        val tile = TileState(tileId = 5, tileType = TileType.ELEMENTAL, currentElement = ElementType.FIRE)
        if (tile.currentElement == player.elementAffinity) {
            token.atk += player.character.atk // * multiplier = 1
        }
        assertEquals(30, token.atk) // default character.atk = 30
    }

    @Test
    fun `element collection non-affinity should increase player MAG`() {
        val player = createTestPlayer(affinity = ElementType.FIRE)
        val initialMag = player.mag
        val tile = TileState(tileId = 8, tileType = TileType.ELEMENTAL, currentElement = ElementType.ICE)
        if (tile.currentElement != player.elementAffinity) {
            player.mag += player.character.mag
        }
        assertEquals(initialMag + 10, player.mag)
    }

    @Test
    fun `full element queue overflow should remove oldest element`() {
        val player = createTestPlayer()
        player.elementQueue.addAll(listOf(ElementType.FIRE, ElementType.ICE, ElementType.GRASS))
        val maxQueue = 5 // for test; actual TBD
        player.elementQueue.add(ElementType.ROCK)
        if (player.elementQueue.size > maxQueue) {
            player.elementQueue.removeAt(0)
        }
        assertEquals(listOf(ElementType.ICE, ElementType.GRASS, ElementType.ROCK), player.elementQueue)
    }

    @Test
    fun `combo C3 (Triple Threat) should remove three identical elements and apply Tier1 reward`() {
        val state = createTestGameState()
        val player = state.currentPlayer
        player.elementQueue.addAll(listOf(ElementType.FIRE, ElementType.FIRE, ElementType.FIRE))
        // Detect combo (simplified)
        val combo = detectCombo(player.elementQueue)
        assertNotNull(combo)
        assertEquals("C3", combo.type)
        // Apply reward
        player.tokens.forEach { it.atk += BalanceConfig.COMBO_T1_ATK_BONUS }
        // Remove combo elements
        repeat(3) { player.elementQueue.removeAt(combo.startIndex) }
        assertTrue(player.elementQueue.isEmpty())
        assertEquals(3, player.tokens.sumOf { it.atk }) // each token +150? Actually each token ATK increase individually
    }

    @Test
    fun `combo C4 (Elemental Master) with four distinct elements`() {
        val player = createTestPlayer()
        player.elementQueue.addAll(listOf(ElementType.FIRE, ElementType.ICE, ElementType.GRASS, ElementType.ROCK))
        val distinctCount = player.elementQueue.subList(0,4).distinct().size
        assertEquals(4, distinctCount)
        // In real code, engine would detect C4 at indices 0-3
    }

    @Test
    fun `kick should reduce defender HP and push to nearest safe zone behind`() {
        val state = createTestGameState()
        val attacker = state.currentPlayer.tokens[0].apply { atk = 50 }
        val defender = state.opponent.tokens[0].apply { position = 10 }
        val defenderInitialHP = state.opponent.hp
        // Simulate kick
        state.opponent.hp -= attacker.atk
        val newPos = findNearestSafeZoneBackward(defender.position)
        assertEquals(defenderInitialHP - 50, state.opponent.hp)
        assertTrue(newPos in SAFE_ZONE_IDS)
    }

    @Test
    fun `kick on safe zone should not occur`() {
        val tile = TileState(tileId = 51, tileType = TileType.SAFE_ZONE)
        val shouldKick = tile.tileType != TileType.SAFE_ZONE
        assertFalse(shouldKick)
    }

    @Test
    fun `final goal processing should add chosen element and attack opponent then return to safe zone`() {
        val state = createTestGameState()
        val token = state.currentPlayer.tokens[0].apply { position = FINAL_GOAL_ID }
        val opponentInitialHP = state.opponent.hp
        // Process final goal
        player.elementQueue.add(ElementType.ICE) // player chooses element
        // Attack opponent: opponent HP -= token.atk
        state.opponent.hp -= token.atk
        // Token returns to safe zone
        token.position = PLAYER_SAFE_ZONE_ID
        // Check results
        assertTrue(state.opponent.hp < opponentInitialHP)
        assertEquals(PLAYER_SAFE_ZONE_ID, token.position)
    }

    @Test
    fun `mag accumulation from non-affinity elements`() {
        val player = createTestPlayer(affinity = ElementType.FIRE)
        player.mag = 0
        val tile = TileState(tileId = 2, tileType = TileType.ELEMENTAL, currentElement = ElementType.ICE)
        if (tile.currentElement != player.elementAffinity) {
            player.mag += player.character.mag // 10
        }
        assertEquals(10, player.mag)
    }

    @Test
    fun `ultimate extra roll should deduct 50 MAG and grant extra turn if cap not reached`() {
        val state = createTestGameState()
        state.currentPlayer.mag = 60
        state.currentPlayer.consecutiveRollsThisTurn = 1
        if (state.currentPlayer.mag >= 50 && state.currentPlayer.consecutiveRollsThisTurn < 3) {
            state.currentPlayer.mag -= 50
            state.extraRollsGranted++
        }
        assertEquals(10, state.currentPlayer.mag)
        assertEquals(1, state.extraRollsGranted)
    }

    @Test
    fun `artifact selection on empty tile should show available artifacts`() {
        val player = createTestPlayer()
        player.emptyTileVisits = 2
        val available = getAvailableArtifacts(player)
        // Swap unlocked at 1, Change at 2, Charge at 3
        assertTrue(available.contains("Swap"))
        assertTrue(available.contains("Change"))
        assertFalse(available.contains("Charge"))
    }

    @Test
    fun `artifact swap requires queue length >= 2`() {
        val player = createTestPlayer()
        player.elementQueue.addAll(listOf(ElementType.FIRE))
        val canSwap = player.elementQueue.size >= 2
        assertFalse(canSwap)
    }

    @Test
    fun `frozen token should not be selectable for movement`() {
        val token = TokenState(owner = "P1", frozenRounds = 2)
        val selectable = token.frozenRounds == 0
        assertFalse(selectable)
    }

    @Test
    fun `round limit reached should compare HP to determine winner`() {
        val state = createTestGameState().apply {
            p1.hp = 850
            p2.hp = 820
            currentRound = maxRounds
            determineWinner()
        }
        assertEquals("P1", state.winner)
    }

    @Test
    fun `tie-break: equal HP gives Player2 win (last mover)`() {
        val state = createTestGameState().apply {
            p1.hp = 600
            p2.hp = 600
            currentRound = maxRounds
            determineWinner()
        }
        assertEquals("P2", state.winner)
    }

    // --- Error Path / Edge Cases ---

    @Test
    fun `error path: Power Roll without target range selection should be ignored`() {
        val handler = TurnHandler()
        val onRoll = { target: IntRange? -> requireNotNull(target) { "target range required" } }
        val error = runCatching { onRoll(null) }
        assertTrue(error.isFailure)
    }

    @Test
    fun `error path: Invalid artifact type should throw`() {
        val player = createTestPlayer()
        player.emptyTileVisits = 3
        assertThrows<IllegalArgumentException> {
            executeArtifact(player, "UnknownArtifact")
        }
    }

    @Test
    fun `edge: Roll Double during cooldown ignores extra turn`() {
        val state = createTestGameState()
        state.currentPlayer.doubleRollCooldown = 1 // active
        val dice = Pair(6,6)
        var extra = false
        if (state.currentPlayer.doubleRollCooldown > 0) {
            extra = false
        } else if (dice.first == dice.second) {
            extra = true
        }
        assertFalse(extra)
    }

    @Test
    fun `edge: Multiple tokens from same player reaching final goal in same turn processed independently`() {
        val player = createTestPlayer()
        player.tokens.add(TokenState(owner=player.id, position=FINAL_GOAL_ID))
        player.tokens.add(TokenState(owner=player.id, position=FINAL_GOAL_ID))
        val initialQueueSize = player.elementQueue.size
        player.tokens.forEach { token ->
            // Each token: add element, attack opponent, return to safe zone
            player.elementQueue.add(ElementType.FIRE)
            // opponent HP reduced by token.atk (assume 0 here)
            token.position = PLAYER_SAFE_ZONE_ID
        }
        assertEquals(initialQueueSize + 2, player.elementQueue.size)
        assertTrue(player.tokens.all { it.position == PLAYER_SAFE_ZONE_ID })
    }

    @Test
    fun `edge: Combo cascade after queue update should apply all combos`() {
        val player = createTestPlayer()
        player.elementQueue.addAll(listOf(ElementType.FIRE, ElementType.FIRE, ElementType.FIRE, ElementType.ICE, ElementType.GRASS, ElementType.ROCK))
        // First C3 removes indices 0-2; after removal, remaining [ICE, GRASS, ROCK] distinct but not 4, so no C4
        val combos = detectAllCombos(player.elementQueue)
        assertEquals(1, combos.size)
        assertEquals("C3", combos[0].type)
    }

}

// --- Minimal Test Doubles (replace with real implementations) ---

fun createTestGameState(): GameState {
    return GameState(
        matchId = "test-1",
        currentPlayer = createTestPlayer(id="P1"),
        opponent = createTestPlayer(id="P2"),
        board = listOf(TileState(0, TileType.ELEMENTAL, ElementType.FIRE), /* ... more */),
        maxRounds = 15,
        currentRound = 1
    )
}

fun createTestPlayer(id: String = "P1"): PlayerState {
    return PlayerState(
        id = id,
        hp = 1000,
        mag = 0,
        elementAffinity = ElementType.FIRE,
        elementQueue = mutableListOf(),
        tokens = mutableListOf(TokenState(owner=id, position=0, atk=0)),
        character = CharacterConfig(affinity = ElementType.FIRE, atk = 30, mag = 10, hp = 1000)
    )
}

object BalanceConfig {
    const val COMBO_T1_ATK_BONUS = 150
    const val DOUBLE_ROLL_COOLDOWN_ROUNDS = 2
    const val MAX_CONSECUTIVE_ROLLS = 3
    const val ULTIMATE_COST_EXTRA_ROLL = 50
    // etc.
}

// Placeholder data
val FINAL_GOAL_ID = 31
val PLAYER_SAFE_ZONE_ID = 51
val SAFE_ZONE_IDS = listOf(0, 51, 25, 31)

fun detectCombo(queue: List<ElementType>): ComboResult? {
    // Simplified: returns first C3 found
    for (i in 0 until queue.size - 2) {
        if (queue[i] == queue[i+1] && queue[i] == queue[i+2]) {
            return ComboResult(type = "C3", startIndex = i, elements = listOf(queue[i], queue[i+1], queue[i+2]))
        }
    }
    return null
}

fun detectAllCombos(queue: List<ElementType>): List<ComboResult> {
    // Not fully implemented: placeholder
    return listOf()
}

fun findNearestSafeZoneBackward(tileId: Int): Int {
    // Simplified backward search in MAIN_LOOP reversed
    MAIN_LOOP.reversed().forEach { if (SAFE_ZONE_IDS.contains(it)) return it }
    return SAFE_ZONE_IDS.first()
}

val MAIN_LOOP = (0..60).toList() // placeholder

fun executeArtifact(player: PlayerState, artifactType: String) {
    when (artifactType) {
        "Swap" -> {
            require(player.elementQueue.size >= 2) { "Queue must have at least 2 elements for Swap" }
            // perform swap
        }
        "Charge" -> {
            player.elementQueue.add(player.elementAffinity)
        }
        else -> throw IllegalArgumentException("Unknown artifact: $artifactType")
    }
}

fun getAvailableArtifacts(player: PlayerState): List<String> {
    val list = mutableListOf<String>()
    if (player.emptyTileVisits >= 1) list.add("Swap")
    if (player.emptyTileVisits >= 2) list.add("Change")
    if (player.emptyTileVisits >= 3) list.add("Charge")
    return list
}

// Data classes (simplified)
data class GameState(
    val matchId: String,
    val currentPlayer: PlayerState,
    val opponent: PlayerState,
    val board: List<TileState>,
    val maxRounds: Int,
    var currentRound: Int,
    var winner: String? = null
) {
    fun determineWinner() {
        if (currentRound >= maxRounds) {
            winner = if (currentPlayer.hp > opponent.hp) currentPlayer.id else if (opponent.hp > currentPlayer.hp) opponent.id else "P2"
        }
    }
}

data class PlayerState(
    val id: String,
    var hp: Int,
    var mag: Int,
    val elementAffinity: ElementType,
    val elementQueue: MutableList<ElementType>,
    val tokens: MutableList<TokenState>,
    val character: CharacterConfig,
    var doubleRollCooldown: Int = 0,
    var consecutiveRollsThisTurn: Int = 0,
    var ultimateExtraRolls: Int = 0,
    var emptyTileVisits: Int = 0,
    var kickCount: Int = 0,
    var finishedHorseCount: Int = 0,
    var extraRollsGranted: Int = 0
)

data class TokenState(
    val owner: String,
    var position: Int,
    var atk: Int,
    var frozenRounds: Int
)

data class TileState(
    val tileId: Int,
    val tileType: TileType,
    val baseElement: ElementType? = null,
    val currentElement: ElementType? = null
)

enum class TileType { ELEMENTAL, EMPTY, SAFE_ZONE, START }

enum class ElementType { FIRE, ICE, GRASS, ROCK }

data class CharacterConfig(
    val affinity: ElementType,
    val atk: Int,
    val mag: Int,
    val hp: Int
)

data class ComboResult(val type: String, val startIndex: Int, val elements: List<ElementType>)
