// src/tests/gdd-overview-v2-elemental-hunter.test.js
// Generated by: agent_qc from GDD-gdd-overview-v2-elemental-hunter.md (sections 2 + 4 + 8)
// Date: 2026-03-18

const {
  createBoard, createToken, createPlayer, createGameState,
  rollDice, moveToken, processTileEffect, checkCombo,
  processKick, processFinalGoal, activateUltimate, useArtifact,
  checkWinCondition, canSelectToken, reduceCooldowns
} = require('../game-engine');

describe('Elemental Hunter — GDD Overview v2', () => {

  // =============================================
  // SECTION 2: Core Mechanics — Board & Tokens
  // =============================================
  describe('Board & Token Setup', () => {
    test('board has 61 tiles (ID 0-60)', () => {
      const board = createBoard();
      expect(board.tiles.length).toBe(61);
    });

    test('each player starts with 3 tokens on their Arm Path', () => {
      const state = createGameState();
      const p1Tokens = state.tokens.filter(t => t.owner === 'P1');
      const p2Tokens = state.tokens.filter(t => t.owner === 'P2');
      expect(p1Tokens.length).toBe(3);
      expect(p2Tokens.length).toBe(3);
    });

    test('initial tokens do not overlap (different tiles)', () => {
      const state = createGameState();
      const positions = state.tokens.map(t => t.position);
      const unique = new Set(positions);
      expect(unique.size).toBe(positions.length);
    });

    test('token starts with atk=0 and frozenRounds=0', () => {
      const token = createToken({ id: 0, owner: 'P1' });
      expect(token.atk).toBe(0);
      expect(token.frozenRounds).toBe(0);
    });
  });

  // =============================================
  // SECTION 2: Core Mechanics — Turn Structure
  // =============================================
  describe('Turn Structure', () => {
    test('roll 2 dice returns values between 1-6 each', () => {
      for (let i = 0; i < 100; i++) {
        const [d1, d2] = rollDice();
        expect(d1).toBeGreaterThanOrEqual(1);
        expect(d1).toBeLessThanOrEqual(6);
        expect(d2).toBeGreaterThanOrEqual(1);
        expect(d2).toBeLessThanOrEqual(6);
      }
    });

    test('token cannot be selected if frozenRounds > 0', () => {
      const token = createToken({ id: 0, owner: 'P1', frozenRounds: 2 });
      expect(canSelectToken(token)).toBe(false);
    });

    test('token can be selected if frozenRounds is 0', () => {
      const token = createToken({ id: 0, owner: 'P1', frozenRounds: 0 });
      expect(canSelectToken(token)).toBe(true);
    });

    test('move token exactly sum-of-dice steps along path', () => {
      const state = createGameState();
      const token = state.tokens[0];
      const startPos = token.position;
      const steps = 7;
      moveToken(state, token, steps);
      expect(token.position).toBe(startPos + steps); // simplified; real path wraps
    });

    test('cannot move to tile occupied by same-owner token', () => {
      const state = createGameState();
      const token1 = state.tokens[0]; // P1
      const token2 = state.tokens[1]; // P1, same owner
      token2.position = token1.position + 3;
      // Try to move token1 to token2's position
      const result = moveToken(state, token1, 3);
      expect(result.valid).toBe(false);
    });
  });

  // =============================================
  // SECTION 2: Tile Effects
  // =============================================
  describe('Tile Effects', () => {
    test('Elemental Tile (matching Affinity) increases ATK', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.character = { affinity: 'Fire', atk: 30, mag: 10 };
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Elemental';
      tile.currentElement = 'Fire';
      token.atk = 0;

      processTileEffect(state, token, tile);
      expect(token.atk).toBe(30);
    });

    test('Elemental Tile (non-matching Affinity) increases MAG', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.character = { affinity: 'Fire', atk: 30, mag: 10 };
      player.mag = 0;
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Elemental';
      tile.currentElement = 'Ice';

      processTileEffect(state, token, tile);
      expect(player.mag).toBe(10);
    });

    test('Elemental Tile (matching Affinity, multiplier=2) doubles ATK gain', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.character = { affinity: 'Fire', atk: 30, mag: 10 };
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Elemental';
      tile.currentElement = 'Fire';
      tile.tileGainMultiplier = 2;
      token.atk = 0;

      processTileEffect(state, token, tile);
      expect(token.atk).toBe(60);
    });

    test('Element added to end of Element Queue', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.elementQueue = ['Ice'];
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Elemental';
      tile.currentElement = 'Fire';

      processTileEffect(state, token, tile);
      expect(player.elementQueue[player.elementQueue.length - 1]).toBe('Fire');
    });

    test('Safe Zone has no effect on token or player', () => {
      const state = createGameState();
      const player = state.players['P1'];
      const token = state.tokens[0];
      token.atk = 10;
      player.mag = 5;
      const tile = state.board.tiles[token.position];
      tile.type = 'Safe';

      processTileEffect(state, token, tile);
      expect(token.atk).toBe(10);
      expect(player.mag).toBe(5);
    });

    test('Elemental Tile element set to null after collection', () => {
      const state = createGameState();
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Elemental';
      tile.currentElement = 'Fire';

      processTileEffect(state, token, tile);
      expect(tile.currentElement).toBeNull();
    });

    test('Empty Tile increments emptyTileVisits', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.emptyTileVisits = 0;
      const token = state.tokens[0];
      const tile = state.board.tiles[token.position];
      tile.type = 'Empty';

      processTileEffect(state, token, tile);
      expect(player.emptyTileVisits).toBe(1);
    });
  });

  // =============================================
  // SECTION 2: Combo System
  // =============================================
  describe('Combo System', () => {
    test('C3: three consecutive same elements detected and removed', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Ice', 'Fire', 'Fire', 'Fire'];
      const tokens = [
        createToken({ id: 0, owner: 'P1', atk: 10 }),
        createToken({ id: 1, owner: 'P1', atk: 10 }),
        createToken({ id: 2, owner: 'P1', atk: 10 }),
      ];

      const result = checkCombo(player, tokens);
      expect(result.comboType).toBe('C3');
      expect(player.comboCount).toBe(1);
      // After removal, the 3 consecutive fires should be gone
      expect(player.elementQueue).not.toContainEqual('Fire');
    });

    test('C4: four different elements detected and removed', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Ice', 'Grass', 'Rock'];
      const tokens = [
        createToken({ id: 0, owner: 'P1', atk: 10 }),
      ];

      const result = checkCombo(player, tokens);
      expect(result.comboType).toBe('C4');
    });

    test('C3 takes priority over C4 when both possible', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      // Queue where C3 (Fire,Fire,Fire) exists alongside 4 different
      player.elementQueue = ['Ice', 'Grass', 'Rock', 'Fire', 'Fire', 'Fire'];
      const tokens = [
        createToken({ id: 0, owner: 'P1', atk: 10 }),
      ];

      const result = checkCombo(player, tokens);
      expect(result.comboType).toBe('C3');
    });

    test('C3 Tier1 combo adds +150 ATK to all tokens', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Fire', 'Fire'];
      const tokens = [
        createToken({ id: 0, owner: 'P1', atk: 10 }),
        createToken({ id: 1, owner: 'P1', atk: 20 }),
      ];

      checkCombo(player, tokens);
      expect(tokens[0].atk).toBe(160); // 10 + 150
      expect(tokens[1].atk).toBe(170); // 20 + 150
    });

    test('Cascading combo: removal triggers re-scan', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      // After removing first C3 [Ice,Ice,Ice], we get [Fire,Fire,Fire] which is another C3
      player.elementQueue = ['Ice', 'Ice', 'Ice', 'Fire', 'Fire', 'Fire'];
      const tokens = [createToken({ id: 0, owner: 'P1', atk: 0 })];

      checkCombo(player, tokens);
      expect(player.comboCount).toBe(2); // cascading triggered second combo
    });

    test('maxComboTier enforced by Level', () => {
      const player = createPlayer('P1');
      player.level = 1; // maxComboTier = 1
      player.character = { comboRewards: { tier1: { atkBonus: 150 }, tier2: { multiplier: 2 }, tier3: { multiplier: 1.5 } } };
      player.comboCount = 1;
      // Next combo would be tier 2, but level 1 caps at tier 1
      const result = checkCombo(player, []);
      // Tier 2 should not be applied at level 1
    });
  });

  // =============================================
  // SECTION 2: Combat (Kick)
  // =============================================
  describe('Combat (Kick)', () => {
    test('attacker on defender tile (non-safe) deals damage', () => {
      const state = createGameState();
      const attacker = createToken({ id: 0, owner: 'P1', atk: 75 });
      const defender = createToken({ id: 1, owner: 'P2', position: 10, atk: 20 });
      defender.position = attacker.position;

      state.players['P2'].hp = 1000;
      processKick(state, attacker, defender);
      expect(state.players['P2'].hp).toBe(925); // 1000 - 75
    });

    test('ATK=0 deals no damage', () => {
      const state = createGameState();
      const attacker = createToken({ id: 0, owner: 'P1', atk: 0 });
      const defender = createToken({ id: 1, owner: 'P2', atk: 20 });
      defender.position = attacker.position;

      state.players['P2'].hp = 1000;
      processKick(state, attacker, defender);
      expect(state.players['P2'].hp).toBe(1000);
    });

    test('kicked token pushed to nearest safe zone behind', () => {
      const state = createGameState();
      const attacker = createToken({ id: 0, owner: 'P1', atk: 50, position: 20 });
      const defender = createToken({ id: 1, owner: 'P2', atk: 10, position: 20 });

      processKick(state, attacker, defender);
      // Token should be at a safe zone behind position 20
      const safeZones = state.board.tiles.filter(t => t.type === 'Safe');
      const safeBehind = safeZones.filter(t => t.id < defender.position).pop();
      expect(defender.position).toBe(safeBehind.id);
    });

    test('kick increments attacker kickCount', () => {
      const state = createGameState();
      const attacker = createToken({ id: 0, owner: 'P1', atk: 50 });
      const defender = createToken({ id: 1, owner: 'P2', atk: 10 });
      defender.position = attacker.position;

      attacker.kickCount = 0;
      processKick(state, attacker, defender);
      expect(attacker.kickCount).toBe(1);
    });

    test('cannot kick on Safe Zone tile', () => {
      const state = createGameState();
      const attacker = createToken({ id: 0, owner: 'P1', atk: 50 });
      const defender = createToken({ id: 1, owner: 'P2' });
      defender.position = attacker.position;
      state.board.tiles[attacker.position].type = 'Safe';

      const result = processKick(state, attacker, defender);
      expect(result.kicked).toBe(false);
    });
  });

  // =============================================
  // SECTION 2: Final Goal
  // =============================================
  describe('Final Goal', () => {
    test('token at Final Goal: player selects element, added to queue', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.elementQueue = ['Ice'];
      const token = state.tokens[0];

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(player.elementQueue).toContain('Fire');
    });

    test('token at Final Goal: combo check runs after element added', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Fire'];
      const token = state.tokens[0];
      token.atk = 10;

      processFinalGoal(state, token, 'P1', 'Fire');
      // Should trigger C3 combo: [Fire, Fire] + Fire = 3 consecutive
      expect(player.comboCount).toBe(1);
    });

    test('token at Final Goal: opponent takes damage = ATK', () => {
      const state = createGameState();
      state.players['P2'].hp = 1000;
      const token = createToken({ id: 0, owner: 'P1', atk: 80 });

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(state.players['P2'].hp).toBe(920);
    });

    test('token at Final Goal: token returns to Start tile', () => {
      const state = createGameState();
      const token = state.tokens[0];
      const startPos = state.board.startTiles['P1'];

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(token.position).toBe(startPos);
    });

    test('token at Final Goal: finishedHorseCount increments', () => {
      const state = createGameState();
      const player = state.players['P1'];
      player.finishedHorseCount = 0;
      const token = state.tokens[0];

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(player.finishedHorseCount).toBe(1);
    });

    test('Final Goal with ATK=0: no damage but counts as goal', () => {
      const state = createGameState();
      state.players['P2'].hp = 1000;
      const player = state.players['P1'];
      player.finishedHorseCount = 0;
      const token = createToken({ id: 0, owner: 'P1', atk: 0 });

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(state.players['P2'].hp).toBe(1000); // no damage
      expect(player.finishedHorseCount).toBe(1); // still counts
    });
  });

  // =============================================
  // SECTION 2: Extra Turn & Cooldown
  // =============================================
  describe('Extra Turn & Cooldown', () => {
    test('Roll Double grants extra turn', () => {
      const state = createGameState();
      const player = state.players['P1'];
      const result = { d1: 4, d2: 4 };
      // Simulate double roll detection
      expect(result.d1).toBe(result.d2); // it's a double
    });

    test('Double Roll sets cooldown for 2 rounds', () => {
      const player = createPlayer('P1');
      player.doubleRollCooldown = 0;
      // After double roll
      player.doubleRollCooldown = 2;
      expect(player.doubleRollCooldown).toBe(2);
    });

    test('During cooldown, double result not treated as Roll Double', () => {
      const player = createPlayer('P1');
      player.doubleRollCooldown = 2;
      // Even if dice match, should not grant extra turn
      const isDouble = false; // suppressed by cooldown
      expect(player.doubleRollCooldown).toBeGreaterThan(0);
    });

    test('Ultimate Extra Roll costs exactly 50 MAG', () => {
      const player = createPlayer('P1');
      player.mag = 50;
      activateUltimate(player);
      expect(player.mag).toBe(0);
      expect(player.ultimateExtraRolls).toBe(1);
    });

    test('Cannot activate Ultimate if MAG < 50', () => {
      const player = createPlayer('P1');
      player.mag = 49;
      expect(() => activateUltimate(player)).toThrow();
    });

    test('Consecutive Roll Cap (3) blocks further extra turns', () => {
      const state = createGameState();
      state.consecutiveRollsThisTurn = 3;
      // MAX_CONSECUTIVE_ROLLS = 3, so no more extra turns
      const canExtra = state.consecutiveRollsThisTurn < 3;
      expect(canExtra).toBe(false);
    });

    test('consecutiveRollsThisTurn resets on player switch', () => {
      const state = createGameState();
      state.consecutiveRollsThisTurn = 2;
      state.currentPlayer = 'P1';
      // Switch to P2
      state.currentPlayer = 'P2';
      state.consecutiveRollsThisTurn = 0;
      expect(state.consecutiveRollsThisTurn).toBe(0);
    });
  });

  // =============================================
  // SECTION 2: MAG & Ultimate
  // =============================================
  describe('MAG & Ultimate', () => {
    test('MAG accumulates on non-Affinity landing', () => {
      const player = createPlayer('P1');
      player.character = { affinity: 'Fire', mag: 10 };
      player.mag = 0;
      // Landing on Ice (non-affinity) — handled in tile effect
      player.mag += player.character.mag;
      expect(player.mag).toBe(10);
    });

    test('MAG capped at magCap', () => {
      const player = createPlayer('P1');
      player.magCap = 100;
      player.mag = 95;
      const gain = 10;
      const actualGain = Math.min(gain, player.magCap - player.mag);
      player.mag += actualGain;
      expect(player.mag).toBe(100);
      expect(actualGain).toBe(5);
    });
  });

  // =============================================
  // SECTION 2: Artifacts
  // =============================================
  describe('Artifacts', () => {
    test('Swap: swap 2 adjacent elements in queue', () => {
      const player = createPlayer('P1');
      player.elementQueue = ['Fire', 'Ice', 'Grass'];
      // Swap indices 0 and 1
      const result = useArtifact(player, 'Swap', { indexA: 0, indexB: 1 });
      expect(player.elementQueue).toEqual(['Ice', 'Fire', 'Grass']);
    });

    test('Change: convert 1 element to another type', () => {
      const player = createPlayer('P1');
      player.elementQueue = ['Fire', 'Ice', 'Grass'];
      // Change index 2 from Grass to Rock
      useArtifact(player, 'Change', { index: 2, newElement: 'Rock' });
      expect(player.elementQueue[2]).toBe('Rock');
    });

    test('Charge: add player Affinity element to end of queue', () => {
      const player = createPlayer('P1');
      player.character = { affinity: 'Fire' };
      player.elementQueue = ['Ice'];
      useArtifact(player, 'Charge', {});
      expect(player.elementQueue).toEqual(['Ice', 'Fire']);
    });

    test('After artifact use, combo check runs', () => {
      const player = createPlayer('P1');
      player.character = { affinity: 'Fire', comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Fire'];
      useArtifact(player, 'Charge', {});
      // Now [Fire, Fire, Fire] — should trigger C3
      expect(player.comboCount).toBe(1);
    });

    test('Swap disabled when queue has < 2 elements', () => {
      const player = createPlayer('P1');
      player.elementQueue = ['Fire'];
      const canSwap = player.elementQueue.length >= 2;
      expect(canSwap).toBe(false);
    });

    test('Change disabled when queue has < 1 element', () => {
      const player = createPlayer('P1');
      player.elementQueue = [];
      const canChange = player.elementQueue.length >= 1;
      expect(canChange).toBe(false);
    });

    test('Unlock Swap at emptyTileVisits >= 1', () => {
      const player = createPlayer('P1');
      player.emptyTileVisits = 1;
      expect(player.emptyTileVisits).toBeGreaterThanOrEqual(1);
    });

    test('Unlock Change at emptyTileVisits >= 2', () => {
      const player = createPlayer('P1');
      player.emptyTileVisits = 2;
      expect(player.emptyTileVisits).toBeGreaterThanOrEqual(2);
    });

    test('Unlock Charge at emptyTileVisits >= 3', () => {
      const player = createPlayer('P1');
      player.emptyTileVisits = 3;
      expect(player.emptyTileVisits).toBeGreaterThanOrEqual(3);
    });
  });

  // =============================================
  // SECTION 3: Win Conditions
  // =============================================
  describe('Win Conditions', () => {
    test('KO: player HP <= 0 → opponent wins', () => {
      const state = createGameState();
      state.players['P1'].hp = 0;
      const result = checkWinCondition(state);
      expect(result.winner).toBe('P2');
      expect(result.reason).toBe('KO');
    });

    test('After maxRounds, higher HP wins', () => {
      const state = createGameState();
      state.currentRound = state.maxRounds;
      state.players['P1'].hp = 800;
      state.players['P2'].hp = 600;
      const result = checkWinCondition(state);
      expect(result.winner).toBe('P1');
      expect(result.reason).toBe('HP');
    });

    test('HP tie at round limit → Player2 wins', () => {
      const state = createGameState();
      state.currentRound = state.maxRounds;
      state.players['P1'].hp = 500;
      state.players['P2'].hp = 500;
      const result = checkWinCondition(state);
      expect(result.winner).toBe('P2');
      expect(result.reason).toBe('TieBreaker');
    });
  });

  // =============================================
  // SECTION 4: Edge Cases
  // =============================================
  describe('Edge Cases', () => {
    test('frozenRounds decrease by 1 at end of each round', () => {
      const token = createToken({ id: 0, owner: 'P1', frozenRounds: 3 });
      token.frozenRounds = Math.max(0, token.frozenRounds - 1);
      expect(token.frozenRounds).toBe(2);
    });

    test('Element Queue full: pop oldest, then add, then check combo', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      const MAX_QUEUE = 5;
      player.elementQueue = ['Fire', 'Ice', 'Grass', 'Rock', 'Ice'];
      // Add Fire — queue exceeds max, pop head
      player.elementQueue.push('Fire');
      if (player.elementQueue.length > MAX_QUEUE) {
        player.elementQueue.shift();
      }
      // Queue should be [Ice, Grass, Rock, Ice, Fire] (Fire popped from head)
      expect(player.elementQueue.length).toBe(MAX_QUEUE);
      expect(player.elementQueue[0]).toBe('Ice');
    });

    test('Token same-owner on same tile → blocked', () => {
      const state = createGameState();
      const token1 = state.tokens[0]; // P1
      const token2 = state.tokens[1]; // P1
      token2.position = 15;
      token1.position = 15; // try to move to same tile
      // Check if blocked
      const blocking = state.tokens.some(t =>
        t.id !== token1.id && t.owner === token1.owner && t.position === token1.position
      );
      expect(blocking).toBe(true);
    });

    test('Power Roll without target = normal random roll', () => {
      const result = rollDice(); // no target range = normal
      expect(result.length).toBe(2);
      expect(result[0]).toBeGreaterThanOrEqual(1);
      expect(result[0]).toBeLessThanOrEqual(6);
    });

    test('Consecutive roll cap blocks both double and ultimate extra turns', () => {
      const state = createGameState();
      state.consecutiveRollsThisTurn = 3; // at cap
      const canGetExtra = state.consecutiveRollsThisTurn < 3;
      expect(canGetExtra).toBe(false);
      // Applies to BOTH double roll and ultimate
    });
  });

  // =============================================
  // SECTION 8: Test Scenarios
  // =============================================
  describe('GDD Test Scenarios', () => {
    test('TS-01: Token moves 7 steps (4+3) and tile effect triggers', () => {
      const state = createGameState();
      const token = state.tokens[0];
      const startPos = token.position;
      const [d1, d2] = [4, 3];
      moveToken(state, token, d1 + d2);
      expect(token.position).toBe(startPos + 7);
      // Tile effect should trigger based on tile type
    });

    test('TS-02: Queue [Fire,Ice,Fire] + Fire → C3, +150 ATK, queue [Fire,Ice]', () => {
      const player = createPlayer('P1');
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Fire', 'Ice', 'Fire', 'Fire'];
      const tokens = [
        createToken({ id: 0, owner: 'P1', atk: 10 }),
      ];
      // Add Fire → [Fire, Ice, Fire, Fire, Fire] — C3 at indices 2-4
      const result = checkCombo(player, tokens);
      expect(player.comboCount).toBe(1);
      expect(tokens[0].atk).toBe(160);
    });

    test('TS-03: ATK 75 attacker kicks defender → -75 HP, kick to safe zone', () => {
      const state = createGameState();
      state.players['P2'].hp = 1000;
      const attacker = createToken({ id: 0, owner: 'P1', atk: 75, position: 20 });
      const defender = createToken({ id: 1, owner: 'P2', atk: 10, position: 20 });

      processKick(state, attacker, defender);
      expect(state.players['P2'].hp).toBe(925);
      // Defend token should be at safe zone behind position 20
      expect(defender.position).toBeLessThan(20);
    });

    test('TS-04: Final Goal → select element, combo check, attack, return to start', () => {
      const state = createGameState();
      state.players['P2'].hp = 1000;
      const player = state.players['P1'];
      player.finishedHorseCount = 0;
      player.character = { comboRewards: { tier1: { atkBonus: 150 } } };
      player.elementQueue = ['Ice'];
      const token = createToken({ id: 0, owner: 'P1', atk: 60 });

      processFinalGoal(state, token, 'P1', 'Fire');
      expect(player.elementQueue).toContain('Fire');
      expect(state.players['P2'].hp).toBe(940); // 1000 - 60
      expect(token.position).toBe(state.board.startTiles['P1']);
      expect(player.finishedHorseCount).toBe(1);
    });

    test('TS-05: MAG >= 50, Ultimate → -50 MAG, extraRoll++, extra turn after', () => {
      const player = createPlayer('P1');
      player.mag = 50;
      player.ultimateExtraRolls = 0;
      activateUltimate(player);
      expect(player.mag).toBe(0);
      expect(player.ultimateExtraRolls).toBe(1);
      // After turn, extra roll should be consumed
    });
  });
});
