// src/tests/ladder-mechanic.test.js
// Generated by: agent_dev from GDD-FEATURE-ladder-mechanic.md (sections 2–4 + 8)
// Updated: 2026-03-18 (bounce-back, Safe Zone gate condition, diamond naming)

// Mock gv.bus
global.gv = { bus: { emit: jest.fn() } };

// Load module (global object literal pattern)
require('../ladder-mechanic.js');

describe('LadderMechanic', () => {

  var defaultConfig = {
    WIN_DIAMOND_THRESHOLD: 600,
    REWARD_TILE_GRANT: 100 // placeholder TBD — test with 100 for now
  };

  beforeEach(() => {
    LadderMechanic.init(defaultConfig);
    jest.clearAllMocks();
  });

  // ── GDD-FEATURE §2.1: REWARD Tile DIAMOND Grant ───────────
  describe('grantRewardDiamond', () => {
    test('grants DIAMOND on REWARD tile (ID 5)', () => {
      var player = { diamond: 0 };
      var result = LadderMechanic.grantRewardDiamond(player, 5);
      expect(result).toBe(100);
      expect(player.diamond).toBe(100);
    });

    test('accumulates DIAMOND across multiple REWARD tiles', () => {
      var player = { diamond: 200 };
      LadderMechanic.grantRewardDiamond(player, 10);
      expect(player.diamond).toBe(300);
      LadderMechanic.grantRewardDiamond(player, 15);
      expect(player.diamond).toBe(400);
    });

    test('returns -1 for non-REWARD tile', () => {
      var player = { diamond: 0 };
      var result = LadderMechanic.grantRewardDiamond(player, 7);
      expect(result).toBe(-1);
      expect(player.diamond).toBe(0);
    });

    test('all REWARD tile IDs are recognized', function() {
      var player = { diamond: 0 };
      LadderMechanic.REWARD_TILE_IDS.forEach(function(id) {
        player.diamond = 0;
        var result = LadderMechanic.grantRewardDiamond(player, id);
        expect(result).toBe(100);
      });
    });
  });

  // ── GDD-FEATURE §2.2: Gate Opening (diamond + Safe Zone) ──
  describe('checkGateOpen', () => {
    test('gate does NOT open when diamond < 600 on Safe Zone', () => {
      var player = { diamond: 599, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 1);
      expect(opened).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('gate opens when diamond >= 600 AND on Safe Zone', () => {
      var player = { diamond: 600, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 1);
      expect(opened).toBe(true);
      expect(player.gateOpen).toBe(true);
    });

    test('gate does NOT open at 600 on non-Safe Zone tile (GDD-FEATURE §4)', () => {
      var player = { diamond: 600, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 7);
      expect(opened).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('gate opens at exactly 600 diamond on Safe Zone (boundary)', () => {
      var player = { diamond: 600, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 11);
      expect(opened).toBe(true);
      expect(player.gateOpen).toBe(true);
    });

    test('gate does NOT re-trigger if already open', () => {
      var player = { diamond: 700, gateOpen: true };
      var opened = LadderMechanic.checkGateOpen(player, 1);
      expect(opened).toBe(false);
    });

    test('gate opens for values well above 600 on Safe Zone', () => {
      var player = { diamond: 9999, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 21);
      expect(opened).toBe(true);
    });

    test('gate opens on any Safe Zone tile when threshold met', function() {
      LadderMechanic.SAFE_ZONE_IDS.forEach(function(id) {
        var player = { diamond: 600, gateOpen: false };
        var opened = LadderMechanic.checkGateOpen(player, id);
        expect(opened).toBe(true);
        expect(player.gateOpen).toBe(true);
      });
    });
  });

  // ── GDD-FEATURE §2.2: forceOpenGate ────────────────────────
  describe('forceOpenGate', () => {
    test('force opens gate even when diamond < 600', () => {
      var player = { diamond: 500, gateOpen: false };
      var opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(true);
      expect(player.gateOpen).toBe(true);
    });

    test('does nothing if gate already open', () => {
      var player = { diamond: 600, gateOpen: true };
      var opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(false);
    });
  });

  // ── GDD-FEATURE §2.3: canEnterLadderLane ───────────────────
  describe('canEnterLadderLane', () => {
    test('can enter when gate open and token on entry gate tile', () => {
      var player = { gateOpen: true };
      var token = { state: 'ON_TRACK', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(true);
    });

    test('cannot enter when gate closed', () => {
      var player = { gateOpen: false };
      var token = { state: 'ON_TRACK', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });

    test('cannot enter when token not on entry gate tile', () => {
      var player = { gateOpen: true };
      var token = { state: 'ON_TRACK', position: 15 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });

    test('cannot enter when token already in ladder lane', () => {
      var player = { gateOpen: true };
      var token = { state: 'IN_LADDER_LANE', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });
  });

  // ── GDD-FEATURE §2.3: enterLadderLane ──────────────────────
  describe('enterLadderLane', () => {
    test('moves token to ladder lane step 0', () => {
      var token = { state: 'ON_TRACK', position: 1 };
      var result = LadderMechanic.enterLadderLane(token);
      expect(result).toBe(true);
      expect(token.state).toBe('IN_LADDER_LANE');
      expect(token.ladderLaneStep).toBe(0);
    });

    test('fails if token not ON_TRACK', () => {
      var token = { state: 'IN_HOME', position: 0 };
      var result = LadderMechanic.enterLadderLane(token);
      expect(result).toBe(false);
    });
  });

  // ── GDD-FEATURE §2.4: advanceInLadderLane — bounce-back ────
  describe('advanceInLadderLane (bounce-back)', () => {
    test('advances token by dice roll within lane', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 0 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 3);
      expect(newStep).toBe(3);
      expect(token.ladderLaneStep).toBe(3);
    });

    test('exact roll to Final Tile (step 5)', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 0 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 5);
      expect(newStep).toBe(5);
      expect(token.ladderLaneStep).toBe(5);
    });

    test('overshoot bounces back: step 3 + roll 4 → bounce to step 4 (GDD-FEATURE §4)', () => {
      // From step 3, 2 remaining to Final (5). Roll 4: overshoot 2, bounce back 2 → step 3
      // Wait: step 3 + 4 = 7, overshoot = 7 - 5 = 2, bounce = 5 - 2 = 3
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 4);
      expect(newStep).toBe(3); // 5 - (7-5) = 3
    });

    test('overshoot from step 4 + roll 6 → bounce to step 3', () => {
      // step 4 + 6 = 10, overshoot = 5, bounce = 5 - 5 = 0
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 6);
      expect(newStep).toBe(0); // 5 - (10-5) = 0
    });

    test('bounce-back clamps to 0 (cannot go negative)', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 0 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 11);
      // 0 + 11 = 11, overshoot = 6, bounce = 5 - 6 = -1 → clamp to 0
      expect(newStep).toBe(0);
    });

    test('exact roll of 1 to Final Tile', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 1);
      expect(newStep).toBe(5);
    });

    test('fails if token not IN_LADDER_LANE', () => {
      var token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      var result = LadderMechanic.advanceInLadderLane(token, 3);
      expect(result).toBe(-1);
    });

    test('bounce-back from step 4 + roll 2 → bounce to step 4', () => {
      // step 4 + 2 = 6, overshoot = 1, bounce = 5 - 1 = 4
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 2);
      expect(newStep).toBe(4);
    });
  });

  // ── GDD-FEATURE §2.4: checkWinCondition ────────────────────
  describe('checkWinCondition', () => {
    test('triggers win when token lands on Final Tile (step 5)', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 5 };
      var won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(true);
      expect(token.state).toBe('FINISHED');
      expect(gv.bus.emit).toHaveBeenCalledWith('GAME_WIN', { playerId: 'player1' });
    });

    test('does NOT trigger win before Final Tile', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      var won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
      expect(token.state).toBe('IN_LADDER_LANE');
    });

    test('does NOT trigger win for token not IN_LADDER_LANE', () => {
      var token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      var won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
    });
  });

  // ── GDD-FEATURE §4: Edge Cases ─────────────────────────────
  describe('edge cases', () => {
    test('gate does not open at 599 diamond even on Safe Zone (GDD-FEATURE §4)', () => {
      var player = { diamond: 599, gateOpen: false };
      expect(LadderMechanic.checkGateOpen(player, 1)).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('two players reach 600 diamond in same round — both gates open (GDD-FEATURE §4)', () => {
      var p1 = { diamond: 600, gateOpen: false };
      var p2 = { diamond: 650, gateOpen: false };
      expect(LadderMechanic.checkGateOpen(p1, 1)).toBe(true);
      expect(LadderMechanic.checkGateOpen(p2, 11)).toBe(true);
      expect(p1.gateOpen).toBe(true);
      expect(p2.gateOpen).toBe(true);
    });

    test('kick blocked in Ladder Lane (GDD-FEATURE §4)', () => {
      var token = { state: 'IN_LADDER_LANE' };
      expect(LadderMechanic.isKickBlocked(token)).toBe(true);
    });

    test('kick NOT blocked for ON_TRACK token', () => {
      var token = { state: 'ON_TRACK' };
      expect(LadderMechanic.isKickBlocked(token)).toBe(false);
    });

    test('gate stays open after being kicked back to Safe Zone (GDD-FEATURE §4)', () => {
      var player = { diamond: 600, gateOpen: true };
      // Simulate kick back to Safe Zone — gateOpen should NOT reset
      expect(player.gateOpen).toBe(true);
    });

    test('cannot win without entering Ladder Lane first', () => {
      var token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      var won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
    });

    test('getRemainingSteps returns correct value', () => {
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 2 };
      expect(LadderMechanic.getRemainingSteps(token)).toBe(3);
    });

    test('getRemainingSteps returns -1 for non-ladder token', () => {
      var token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      expect(LadderMechanic.getRemainingSteps(token)).toBe(-1);
    });
  });

  // ── GDD-FEATURE §9: Test Scenarios ─────────────────────────
  describe('test scenarios from GDD-FEATURE §9', () => {
    test('TS-1: 599 diamond on Safe Zone → gate does NOT open', () => {
      var player = { diamond: 599, gateOpen: false };
      expect(LadderMechanic.checkGateOpen(player, 1)).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TS-2: 600 diamond on Safe Zone → gate opens', () => {
      var player = { diamond: 600, gateOpen: false };
      expect(LadderMechanic.checkGateOpen(player, 11)).toBe(true);
      expect(player.gateOpen).toBe(true);
    });

    test('TS-3: 700 diamond on non-Safe Zone → gate does NOT open', () => {
      var player = { diamond: 700, gateOpen: false };
      var opened = LadderMechanic.checkGateOpen(player, 7);
      expect(opened).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TS-4: kicked back to Safe Zone with gateOpen → gate stays open', () => {
      var player = { diamond: 650, gateOpen: true };
      // Simulate kick-back to Safe Zone 1
      expect(player.gateOpen).toBe(true); // not reset by kick
    });

    test('TS-5: 2 steps to Final, bounce-back on overshoot (roll 5) → step 3', () => {
      // token at step 3 (2 steps to Final). Roll 5: 3+5=8, overshoot=3, bounce=5-3=2
      var token = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 };
      var newStep = LadderMechanic.advanceInLadderLane(token, 5);
      expect(newStep).toBe(2); // bounce-back
    });

    test('TS-6: two players both at 600 diamond → both gates open simultaneously', () => {
      var p1 = { diamond: 600, gateOpen: false };
      var p2 = { diamond: 600, gateOpen: false };
      LadderMechanic.checkGateOpen(p1, 1);
      LadderMechanic.checkGateOpen(p2, 11);
      expect(p1.gateOpen).toBe(true);
      expect(p2.gateOpen).toBe(true);
    });

    test('TS-7: first player to reach Final Tile wins (GDD-FEATURE §3)', () => {
      var t1 = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 }; // 1 step
      var t2 = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 }; // 2 steps

      // Player 1 rolls exact 1 → wins
      LadderMechanic.advanceInLadderLane(t1, 1);
      expect(LadderMechanic.checkWinCondition(t1, 'p1')).toBe(true);

      // Player 2 hasn't moved yet
      expect(t2.ladderLaneStep).toBe(3);
      expect(LadderMechanic.checkWinCondition(t2, 'p2')).toBe(false);
    });
  });
});
