// src/tests/ladder-mechanic.test.js
// Generated by: agent_qc from GDD-FEATURE-ladder-mechanic.md (sections 2, 4, 9)
// Hash: 248FDEE59877405709C2B556BD4DEFD2
// Source: src/ladder-mechanic.js (LadderMechanic global object)

// Load source — relies on LadderMechanic global being available
// In test environment, we may need to load via require or vm.runInContext
// For Jest, assume source is loaded via setupFiles or moduleNameMapper

// Mock global dependencies
beforeAll(() => {
  global.gv = { bus: { emit: jest.fn() } };
  // Initialize with default config
  if (typeof LadderMechanic !== 'undefined') {
    LadderMechanic.init({
      REWARD_TILE_GRANT: 50,
      WIN_DIAMOND_THRESHOLD: 600
    });
  }
});

beforeEach(() => {
  if (typeof LadderMechanic !== 'undefined') {
    LadderMechanic.reset();
    LadderMechanic.init({
      REWARD_TILE_GRANT: 50,
      WIN_DIAMOND_THRESHOLD: 600
    });
  }
  if (global.gv && global.gv.bus) {
    global.gv.bus.emit.mockClear();
  }
});

describe('LadderMechanic', () => {

  // ─── GDD §2: Core Mechanics ───────────────────────────────

  describe('core mechanics', () => {

    test('TC-L001: grantRewardDiamond — land on Ladder tile adds diamond', () => {
      const player = { diamond: 0 };
      const result = LadderMechanic.grantRewardDiamond(player, 5); // tile 5 = Ladder
      expect(result).toBe(50);
      expect(player.diamond).toBe(50);
    });

    test('TC-L001b: grantRewardDiamond — non-ladder tile returns -1', () => {
      const player = { diamond: 0 };
      const result = LadderMechanic.grantRewardDiamond(player, 99);
      expect(result).toBe(-1);
      expect(player.diamond).toBe(0);
    });

    test('TC-L002: checkGateOpen — diamond >= 600 on Safe Zone opens gate', () => {
      const player = { diamond: 600, gateOpen: false };
      const result = LadderMechanic.checkGateOpen(player, 1); // tile 1 = Green Safe Zone
      expect(result).toBe(true);
      expect(player.gateOpen).toBe(true);
    });

    test('TC-L003: checkGateOpen — diamond = 599 on Safe Zone does NOT open gate', () => {
      const player = { diamond: 599, gateOpen: false };
      const result = LadderMechanic.checkGateOpen(player, 1);
      expect(result).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TC-L004: checkGateOpen — diamond >= 600 but non-Safe Zone does NOT open gate', () => {
      const player = { diamond: 620, gateOpen: false };
      const result = LadderMechanic.checkGateOpen(player, 5); // tile 5 = Ladder, not Safe Zone
      expect(result).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TC-L005: canEnterLadderLane — gate open + ON_TRACK on Safe Zone allows entry', () => {
      const player = { gateOpen: true };
      const token = { state: LadderMechanic.TokenState.ON_TRACK, position: 1 };
      const result = LadderMechanic.canEnterLadderLane(player, token, 1);
      expect(result).toBe(true);
    });

    test('TC-L005b: canEnterLadderLane — gate closed blocks entry', () => {
      const player = { gateOpen: false };
      const token = { state: LadderMechanic.TokenState.ON_TRACK, position: 1 };
      const result = LadderMechanic.canEnterLadderLane(player, token, 1);
      expect(result).toBe(false);
    });

    test('TC-L006: checkWinCondition — on Final Tile (step 5) triggers win', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 5
      };
      const result = LadderMechanic.checkWinCondition(token, 'player1');
      expect(result).toBe(true);
      expect(token.state).toBe(LadderMechanic.TokenState.FINISHED);
      expect(global.gv.bus.emit).toHaveBeenCalledWith('GAME_WIN', { playerId: 'player1' });
    });

    test('TC-L007: checkWinCondition — wrong step (not 5) does NOT trigger win', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 3
      };
      const result = LadderMechanic.checkWinCondition(token, 'player1');
      expect(result).toBe(false);
    });

    test('TC-L007b: checkWinCondition — not in Ladder Lane does NOT trigger win', () => {
      const token = {
        state: LadderMechanic.TokenState.ON_TRACK,
        ladderLaneStep: 0
      };
      const result = LadderMechanic.checkWinCondition(token, 'player1');
      expect(result).toBe(false);
    });
  });

  // ─── GDD §4: Edge Cases ───────────────────────────────────

  describe('edge cases', () => {

    test('TC-L008: Concurrent gate opening — 2 players both get gateOpen', () => {
      const playerA = { diamond: 600, gateOpen: false };
      const playerB = { diamond: 600, gateOpen: false };
      const resultA = LadderMechanic.checkGateOpen(playerA, 1); // Green Safe Zone
      const resultB = LadderMechanic.checkGateOpen(playerB, 11); // Red Safe Zone
      expect(resultA).toBe(true);
      expect(resultB).toBe(true);
      expect(playerA.gateOpen).toBe(true);
      expect(playerB.gateOpen).toBe(true);
    });

    test('TC-L009: Gate stays open after token pushed back (gate is permanent)', () => {
      const player = { diamond: 600, gateOpen: true };
      // Gate is permanent — calling checkGateOpen again returns false (already open)
      const result = LadderMechanic.checkGateOpen(player, 1);
      expect(result).toBe(false); // false because already open, not because it closed
      expect(player.gateOpen).toBe(true); // still open
    });

    test('TC-L010: Overshoot on Ladder Lane — bounce back', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 4 // one step from Final Tile (step 5)
      };
      // Roll 3: would go to step 7, but target is 5, so overshoot = 2, bounce to step 3
      const newStep = LadderMechanic.advanceInLadderLane(token, 3);
      expect(newStep).toBe(3); // 5 - (7-5) = 3
      expect(token.ladderLaneStep).toBe(3);
    });

    test('TC-L010b: Overshoot bounces to 0 (clamp)', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 0 // at start of lane
      };
      // Roll 6: target = 5, overshoot = 1, bounce to 4... wait let me recalc
      // newStep = 0 + 6 = 6, target = 5, overshoot = 1, bounce = 5 - 1 = 4
      const newStep = LadderMechanic.advanceInLadderLane(token, 6);
      expect(newStep).toBe(4);
    });

    test('TC-L011: Diamond accumulates past 600 (not capped)', () => {
      const player = { diamond: 599 };
      LadderMechanic.grantRewardDiamond(player, 5);
      expect(player.diamond).toBe(649); // 599 + 50
    });

    test('TC-L012: Kick blocked when token in Ladder Lane', () => {
      const token = { state: LadderMechanic.TokenState.IN_LADDER_LANE };
      const result = LadderMechanic.isKickBlocked(token);
      expect(result).toBe(true);
    });

    test('TC-L012b: Kick NOT blocked when token on regular track', () => {
      const token = { state: LadderMechanic.TokenState.ON_TRACK };
      const result = LadderMechanic.isKickBlocked(token);
      expect(result).toBe(false);
    });
  });

  // ─── GDD §3: Win Conditions ────────────────────────────────

  describe('win conditions', () => {

    test('TC-L013: First player to reach Final Tile wins game', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 5
      };
      const result = LadderMechanic.checkWinCondition(token, 'playerA');
      expect(result).toBe(true);
      expect(global.gv.bus.emit).toHaveBeenCalledWith('GAME_WIN', { playerId: 'playerA' });
    });

    test('TC-L014: Win only fires when ladderLaneStep exactly equals 5', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 4
      };
      const result = LadderMechanic.checkWinCondition(token, 'playerB');
      expect(result).toBe(false);
    });
  });

  // ─── GDD §9: Test Scenarios ────────────────────────────────

  describe('test scenarios', () => {

    test('TC-L015: Full ladder journey — gain 50 diamond, reach 600, open gate, win', () => {
      // Step 1: land on Ladder tile, gain diamond
      const player = { diamond: 550, gateOpen: false };
      LadderMechanic.grantRewardDiamond(player, 10); // tile 10 = Ladder
      expect(player.diamond).toBe(600);

      // Step 2: land on Safe Zone, gate opens
      const gateOpened = LadderMechanic.checkGateOpen(player, 1);
      expect(gateOpened).toBe(true);

      // Step 3: enter Ladder Lane
      const token = { state: LadderMechanic.TokenState.ON_TRACK, position: 1 };
      const canEnter = LadderMechanic.canEnterLadderLane(player, token, 1);
      expect(canEnter).toBe(true);

      LadderMechanic.enterLadderLane(token);
      expect(token.state).toBe(LadderMechanic.TokenState.IN_LADDER_LANE);
      expect(token.ladderLaneStep).toBe(0);

      // Step 4: advance to Final Tile (roll 5 to reach step 5)
      LadderMechanic.advanceInLadderLane(token, 5);
      expect(token.ladderLaneStep).toBe(5);

      // Step 5: win
      const won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(true);
    });

    test('TC-L016: Insufficient diamond (599) on Safe Zone — gate stays closed', () => {
      const player = { diamond: 599, gateOpen: false };
      const result = LadderMechanic.checkGateOpen(player, 11); // Red Safe Zone
      expect(result).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TC-L017: Diamond >= 600 but wrong tile — gate stays closed', () => {
      const player = { diamond: 620, gateOpen: false };
      const result = LadderMechanic.checkGateOpen(player, 5); // Ladder tile, not Safe Zone
      expect(result).toBe(false);
      expect(player.gateOpen).toBe(false);
    });

    test('TC-L018: Gate persists — permanent once opened', () => {
      const player = { diamond: 600, gateOpen: true };
      expect(player.gateOpen).toBe(true);
      // Even if we try to check again, it stays true
      LadderMechanic.checkGateOpen(player, 21);
      expect(player.gateOpen).toBe(true);
    });

    test('TC-L019: Cannot win on wrong color Ladder tile', () => {
      // Player is Green (target = tile 41 = step 5), but stuck on step 3
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 3
      };
      const result = LadderMechanic.checkWinCondition(token, 'greenPlayer');
      expect(result).toBe(false);
    });
  });

  // ─── GDD §6: Balance & Configuration ──────────────────────

  describe('balance and configuration', () => {

    test('TC-L020: 12 Ladder landings reach exactly 600 diamond', () => {
      const player = { diamond: 0 };
      for (let i = 0; i < 12; i++) {
        LadderMechanic.grantRewardDiamond(player, 5); // any ladder tile
      }
      expect(player.diamond).toBe(600); // 12 * 50 = 600
    });

    test('TC-L021: getRemainingSteps — correct calculation', () => {
      const token = {
        state: LadderMechanic.TokenState.IN_LADDER_LANE,
        ladderLaneStep: 2
      };
      const remaining = LadderMechanic.getRemainingSteps(token);
      expect(remaining).toBe(3); // 5 - 2 = 3
    });

    test('TC-L022: getRemainingSteps — returns -1 when not in Ladder Lane', () => {
      const token = { state: LadderMechanic.TokenState.ON_TRACK };
      const remaining = LadderMechanic.getRemainingSteps(token);
      expect(remaining).toBe(-1);
    });

    test('TC-L006b: Ladder tile IDs are correctly defined', () => {
      expect(LadderMechanic.LADDER_TILE_IDS.green).toBe(41);
      expect(LadderMechanic.LADDER_TILE_IDS.red).toBe(42);
      expect(LadderMechanic.LADDER_TILE_IDS.blue).toBe(43);
      expect(LadderMechanic.LADDER_TILE_IDS.yellow).toBe(44);
    });

    test('TC-L006c: Safe Zone IDs match GDD spec', () => {
      expect(LadderMechanic.SAFE_ZONE_IDS).toEqual([1, 11, 21, 31]);
    });

    test('TC-L001c: Reward tile IDs match GDD spec', () => {
      expect(LadderMechanic.REWARD_TILE_IDS).toEqual([5, 10, 15, 20, 25, 30, 35, 40]);
    });
  });
});
