// src/tests/ladder-mechanic.test.js
// Generated by: agent_qc from GDD-ladder-mechanic.md (sections 4 + 8)
// Generated: 2026-03-18

// Mock gv.bus
global.gv = { bus: { emit: jest.fn() } };

// Load module (global object literal pattern)
require('../ladder-mechanic.js');

describe('LadderMechanic', () => {

  beforeEach(() => {
    LadderMechanic.init({ pointOpenGate: 600 });
    jest.clearAllMocks();
  });

  // ── GDD §2: Core Mechanics — Gate Opening ─────────────────
  describe('gate opening', () => {
    test('gate does NOT open when ladderPoint < 600', () => {
      const player = { ladderPoint: 599, gateOpened: false };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(false);
      expect(player.gateOpened).toBe(false);
    });

    test('gate opens when ladderPoint >= 600', () => {
      const player = { ladderPoint: 600, gateOpened: false };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
    });

    test('gate does NOT re-trigger if already open', () => {
      const player = { ladderPoint: 700, gateOpened: true };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(false);
    });

    test('gate opens at exactly 600 KC (boundary)', () => {
      const player = { ladderPoint: 600, gateOpened: false };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
    });

    test('gate opens for values well above 600', () => {
      const player = { ladderPoint: 9999, gateOpened: false };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(true);
    });
  });

  // ── GDD §2: forceOpenGate (FORCE_OPEN_GATE event) ─────────
  describe('forceOpenGate', () => {
    test('force opens gate even when ladderPoint < 600', () => {
      const player = { ladderPoint: 500, gateOpened: false };
      const opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
    });

    test('does nothing if gate already open', () => {
      const player = { ladderPoint: 600, gateOpened: true };
      const opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(false);
    });
  });

  // ── GDD §2: canEnterLadderLane ─────────────────────────────
  describe('canEnterLadderLane', () => {
    test('can enter when gate open and token on entry gate tile', () => {
      const player = { gateOpened: true };
      const token = { state: 'ON_TRACK', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(true);
    });

    test('cannot enter when gate closed', () => {
      const player = { gateOpened: false };
      const token = { state: 'ON_TRACK', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });

    test('cannot enter when token not on entry gate tile', () => {
      const player = { gateOpened: true };
      const token = { state: 'ON_TRACK', position: 15 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });

    test('cannot enter when token already in ladder lane', () => {
      const player = { gateOpened: true };
      const token = { state: 'IN_LADDER_LANE', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });
  });

  // ── GDD §2: enterLadderLane ────────────────────────────────
  describe('enterLadderLane', () => {
    test('moves token to ladder lane step 0', () => {
      const token = { state: 'ON_TRACK', position: 1 };
      const result = LadderMechanic.enterLadderLane(token);
      expect(result).toBe(true);
      expect(token.state).toBe('IN_LADDER_LANE');
      expect(token.ladderLaneStep).toBe(0);
    });

    test('fails if token not ON_TRACK', () => {
      const token = { state: 'IN_HOME', position: 0 };
      const result = LadderMechanic.enterLadderLane(token);
      expect(result).toBe(false);
    });
  });

  // ── GDD §2: advanceInLadderLane — exact roll rule ──────────
  describe('advanceInLadderLane', () => {
    test('advances token by dice roll within lane', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 0 };
      const newStep = LadderMechanic.advanceInLadderLane(token, 3);
      expect(newStep).toBe(3);
      expect(token.ladderLaneStep).toBe(3);
    });

    test('exact roll to Final Tile (step 5)', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 0 };
      const newStep = LadderMechanic.advanceInLadderLane(token, 5);
      expect(newStep).toBe(5);
    });

    test('overshoot returns -1 and does NOT move token (GDD §4.10)', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      const result = LadderMechanic.advanceInLadderLane(token, 6);
      expect(result).toBe(-1);
      expect(token.ladderLaneStep).toBe(4); // unchanged
    });

    test('overshoot when 1 step remaining', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      const result = LadderMechanic.advanceInLadderLane(token, 2);
      expect(result).toBe(-1);
      expect(token.ladderLaneStep).toBe(4);
    });

    test('exact roll of 1 to Final Tile', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      const newStep = LadderMechanic.advanceInLadderLane(token, 1);
      expect(newStep).toBe(5);
    });

    test('fails if token not IN_LADDER_LANE', () => {
      const token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      const result = LadderMechanic.advanceInLadderLane(token, 3);
      expect(result).toBe(-1);
    });
  });

  // ── GDD §2: checkWinCondition ──────────────────────────────
  describe('checkWinCondition', () => {
    test('triggers win when token lands on Final Tile (step 5)', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 5 };
      const won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(true);
      expect(token.state).toBe('FINISHED');
      expect(gv.bus.emit).toHaveBeenCalledWith('GAME_WIN', { playerId: 'player1' });
    });

    test('does NOT trigger win before Final Tile', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      const won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
      expect(token.state).toBe('IN_LADDER_LANE');
    });

    test('does NOT trigger win for token not IN_LADDER_LANE', () => {
      const token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      const won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
    });
  });

  // ── GDD §4: Edge Cases ─────────────────────────────────────
  describe('edge cases', () => {
    test('edge case: gate opens at 600 regardless of tile position (GDD §4.1)', () => {
      const player = { ladderPoint: 600, gateOpened: false };
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(true);
      // Gate opened even if not on Safe Zone — position checked separately
    });

    test('edge case: two players reach 600 KC in same round — both gates open independently (GDD §4.2)', () => {
      const p1 = { ladderPoint: 600, gateOpened: false };
      const p2 = { ladderPoint: 650, gateOpened: false };
      expect(LadderMechanic.checkGateOpen(p1)).toBe(true);
      expect(LadderMechanic.checkGateOpen(p2)).toBe(true);
      expect(p1.gateOpened).toBe(true);
      expect(p2.gateOpened).toBe(true);
    });

    test('edge case: kick blocked in Ladder Lane (GDD §4.8)', () => {
      const token = { state: 'IN_LADDER_LANE' };
      expect(LadderMechanic.isKickBlocked(token)).toBe(true);
    });

    test('edge case: kick NOT blocked for ON_TRACK token', () => {
      const token = { state: 'ON_TRACK' };
      expect(LadderMechanic.isKickBlocked(token)).toBe(false);
    });

    test('edge case: FORCE_OPEN_GATE event opens gate below 600 KC (GDD §4.6)', () => {
      const player = { ladderPoint: 500, gateOpened: false };
      const opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
    });

    test('edge case: token cannot win without entering Ladder Lane first', () => {
      const token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      const won = LadderMechanic.checkWinCondition(token, 'player1');
      expect(won).toBe(false);
    });

    test('getRemainingSteps returns correct value', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 2 };
      expect(LadderMechanic.getRemainingSteps(token)).toBe(3);
    });

    test('getRemainingSteps returns -1 for non-ladder token', () => {
      const token = { state: 'ON_TRACK', ladderLaneStep: 0 };
      expect(LadderMechanic.getRemainingSteps(token)).toBe(-1);
    });
  });

  // ── GDD §8: Test Scenarios ─────────────────────────────────
  describe('test scenarios from GDD §8', () => {
    test('TS-1: 599 KC on Safe Zone → gate does NOT open', () => {
      const player = { ladderPoint: 599, gateOpened: false };
      expect(LadderMechanic.checkGateOpen(player)).toBe(false);
      expect(player.gateOpened).toBe(false);
    });

    test('TS-2: 600 KC → gate opens, can enter Ladder Lane', () => {
      const player = { ladderPoint: 600, gateOpened: false };
      const token = { state: 'ON_TRACK', position: 1 }; // Green Safe Zone
      expect(LadderMechanic.checkGateOpen(player)).toBe(true);
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(true);
    });

    test('TS-3: 600 KC on non-Safe Zone tile → gate opens but cannot enter yet', () => {
      const player = { ladderPoint: 600, gateOpened: false };
      const token = { state: 'ON_TRACK', position: 15 }; // Ladder tile, not Safe Zone
      const opened = LadderMechanic.checkGateOpen(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(false);
    });

    test('TS-4: gate open + on Safe Zone → enter Ladder Lane', () => {
      const player = { gateOpened: true };
      const token = { state: 'ON_TRACK', position: 1 };
      expect(LadderMechanic.canEnterLadderLane(player, token, 1)).toBe(true);
      const entered = LadderMechanic.enterLadderLane(token);
      expect(entered).toBe(true);
      expect(token.state).toBe('IN_LADDER_LANE');
      expect(token.ladderLaneStep).toBe(0);
    });

    test('TS-5: 2 steps to Final, roll 2 → WIN', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 }; // 2 steps remaining (5-3=2)
      const newStep = LadderMechanic.advanceInLadderLane(token, 2);
      expect(newStep).toBe(5);
      const won = LadderMechanic.checkWinCondition(token, 'p1');
      expect(won).toBe(true);
    });

    test('TS-6: 2 steps to Final, roll 3 → no move, no win', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 };
      const result = LadderMechanic.advanceInLadderLane(token, 3);
      expect(result).toBe(-1);
      expect(token.ladderLaneStep).toBe(3);
      expect(LadderMechanic.checkWinCondition(token, 'p1')).toBe(false);
    });

    test('TS-7: two players race — first to exact roll wins', () => {
      const p1 = { ladderPoint: 700, gateOpened: true };
      const p2 = { ladderPoint: 650, gateOpened: true };
      const t1 = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 }; // 1 step
      const t2 = { state: 'IN_LADDER_LANE', ladderLaneStep: 3 }; // 2 steps

      // Player 1 rolls exact 1 → wins
      LadderMechanic.advanceInLadderLane(t1, 1);
      expect(LadderMechanic.checkWinCondition(t1, 'p1')).toBe(true);
      // Player 2 hasn't moved yet
      expect(t2.ladderLaneStep).toBe(3);
    });

    test('TS-8: kick blocked in Ladder Lane', () => {
      const token = { state: 'IN_LADDER_LANE' };
      expect(LadderMechanic.isKickBlocked(token)).toBe(true);
    });

    test('TS-9: FORCE_OPEN_GATE at 500 KC → gate opens', () => {
      const player = { ladderPoint: 500, gateOpened: false };
      const opened = LadderMechanic.forceOpenGate(player);
      expect(opened).toBe(true);
      expect(player.gateOpened).toBe(true);
    });

    test('TS-10: at tile 5/6 (1 step), roll 6 → overshoot, no win', () => {
      const token = { state: 'IN_LADDER_LANE', ladderLaneStep: 5 }; // already at Final
      // Actually TS-10: tile 4/6 means step 4, 1 remaining
      const token2 = { state: 'IN_LADDER_LANE', ladderLaneStep: 4 };
      const result = LadderMechanic.advanceInLadderLane(token2, 6);
      expect(result).toBe(-1);
      expect(token2.ladderLaneStep).toBe(4);
      expect(LadderMechanic.checkWinCondition(token2, 'p1')).toBe(false);
    });
  });
});
