// src/tests/client/elemental-hunter.test.ts
// Generated by: agent_qc from analysis/REQ-elemental-hunter.md & DESIGN-elemental-hunter.md
// Date: 2026-03-19 10:55 UTC

/**
 * Client-side unit tests for Elemental Hunter feature.
 * Focus: UI logic, event handling, pure functions (dice, artifact selection).
 * Tests should mock Cocos2d-x and network layer.
 */

import { ElementType } from '../../client/elemental-hunter/constants';
import { DiceRoller } from '../../client/elemental-hunter/dice-roller';
import { ArtifactPicker } from '../../client/elemental-hunter/artifact-picker';
import { ElementQueueUI } from '../../client/elemental-hunter/element-queue-ui';

// --- Mocks ---------------------------------------------------------

jest.mock('../../client/elemental-hunter/event-bus');
const MockEventBus = require('../../client/elemental-hunter/event-bus');

// --- Test Suites ---------------------------------------------------

describe('Client: Elemental Hunter — Core Mechanics', () => {

  describe('DiceRoller', () => {
    // Use deterministic RNG for tests: pass seed or override
    test('should roll two dice (sum between 2 and 12)', () => {
      const roller = new DiceRoller();
      const sum = roller.roll(); // override in test: jest.spyOn(Math, 'random')...
      expect(sum).toBeGreaterThanOrEqual(2);
      expect(sum).toBeLessThanOrEqual(12);
    });

    test('should treat power roll target range: 20% probability to land in range', () => {
      const roller = new DiceRoller();
      // We can't test randomness deterministically without mocking; instead test logic:
      const inRange = (result: number, min: number, max: number) => result >= min && result <= max;
      expect(inRange(5, 5, 7)).toBe(true);
      expect(inRange(4, 5, 7)).toBe(false);
    });

    test('power roll without target selection should be ignored', () => {
      const onRoll = jest.fn();
      const roller = new DiceRoller();
      roller.onRoll = onRoll;
      // Simulate player did not set target
      roller.rollWithPowerRoll(null);
      expect(onRoll).not.toHaveBeenCalled();
    });
  });

  describe('ElementQueueUI', () => {
    test('should display queue elements in order', () => {
      const queueUI = new ElementQueueUI();
      queueUI.setQueue([ElementType.FIRE, ElementType.ICE, ElementType.GRASS]);
      const rendered = queueUI.render();
      expect(rendered).toContain('Fire');
      expect(rendered).toContain('Ice');
      expect(rendered).toContain('Grass');
    });

    test('should highlight when queue length equals max', () => {
      const queueUI = new ElementQueueUI();
      queueUI.setQueue([ElementType.FIRE, ElementType.ICE, ElementType.GRASS, ElementType.ROCK]);
      queueUI.setMaxSize(4);
      const isFull = queueUI.isFull();
      expect(isFull).toBe(true);
    });

    test('should clear queue after combo execution', () => {
      const queueUI = new ElementQueueUI();
      queueUI.setQueue([ElementType.FIRE, ElementType.FIRE, ElementType.FIRE]);
      // Sim combo cleared
      queueUI.clear();
      expect(queueUI.isEmpty()).toBe(true);
    });
  });

  describe('ArtifactPicker', () => {
    test('should show only unlocked artifacts based on emptyTileVisits', () => {
      const picker = new ArtifactPicker();
      picker.setEmptyTileVisits(1);
      const available = picker.getAvailableArtifacts();
      expect(available).toContain('Swap');
      expect(available).not.toContain('Change');
      expect(available).not.toContain('Charge');
    });

    test('should allow Swap only when queue length >= 2', () => {
      const picker = new ArtifactPicker();
      picker.setQueue([ElementType.FIRE]); // length 1
      const canSwap = picker.canExecute('Swap');
      expect(canSwap).toBe(false);
    });

    test('on artifact selected, should emit event', () => {
      const picker = new ArtifactPicker();
      const emitSpy = jest.spyOn(MockEventBus, 'emit');
      picker.selectArtifact('Charge');
      expect(emitSpy).toHaveBeenCalledWith('elementalHunter:artifactSelected', { type: 'Charge' });
    });
  });

});

describe('Client: Elemental Hunter — Edge Cases', () => {

  test('edge: Power Roll target selection ignored if no range provided', () => {
    const roller = new DiceRoller();
    roller.setTargetRange(null);
    expect(roller.shouldIgnore()).toBe(true);
  });

  test('edge: Artifact Swap with insufficient queue elements should no-op', () => {
    const picker = new ArtifactPicker();
    picker.setQueue([ElementType.FIRE]);
    const result = picker.execute('Swap');
    expect(result).toBe('noop');
  });

  test('edge: Combo display should cascade correctly when multiple combos happen sequentially', () => {
    const queueUI = new ElementQueueUI();
    // Simulate cascade: after first combo, remaining may trigger another
    queueUI.setQueue([ElementType.FIRE, ElementType.FIRE, ElementType.FIRE, ElementType.ICE, ElementType.GRASS, ElementType.ROCK]);
    const combos = queueUI.detectCombos();
    // First C3 at indices 0-2 removes FIRE x3, leaving [ICE, GRASS, ROCK] — no further combo
    expect(combos).toHaveLength(1);
    expect(combos[0].type).toBe('C3');
  });

});

describe('Client: Elemental Hunter — Win Conditions', () => {

  test('should display KO immediately when opponent HP <= 0', () => {
    const gameState = { p1HP: 500, p2HP: -10 };
    const isKO = gameState.p2HP <= 0;
    expect(isKO).toBe(true);
  });

  test('should determine winner by HP at round limit', () => {
    const p1HP = 800;
    const p2HP = 750;
    const p1Wins = p1HP > p2HP;
    expect(p1Wins).toBe(true);
  });

  test('tie-break: if HP equal, Player2 wins (last mover advantage)', () => {
    const p1HP = 600;
    const p2HP = 600;
    const winner = p1HP > p2HP ? 'P1' : p2HP > p1HP ? 'P2' : 'P2';
    expect(winner).toBe('P2');
  });

});
