// src/tests/client/elemental-hunter.test.ts
// Generated by: agent_qc from analysis REQ/DESIGN (hash changed)
// Layer: Client (TypeScript/Jest) — testing client-side logic and event handling

import { EventEmitter } from 'events';
import { GameClient } from '../../client/elemental-hunter/GameClient';

// Mock dependencies
class MockBoardRenderer {
  render() {}
}
class MockTokenRenderer {
  update() {}
}
class MockDiceUI {
  roll() {}
}
class MockArtifactUI {
  select() {}
}

describe('ElementalHunterClient', () => {
  let client: GameClient;
  let mockEventBus: EventEmitter;

  beforeEach(() => {
    mockEventBus = new EventEmitter();
    client = new GameClient(mockEventBus as any);
  });

  // Use Cases from REQ (happy path)
  describe('use cases', () => {
    test('should roll dice and receive result event', () => {
      // Arrange
      const spy = jest.fn();
      mockEventBus.on('EVT_DICE_RESULT', spy);
      // Act
      client.rollDice();
      // Assert
      expect(spy).toHaveBeenCalledWith(expect.objectContaining({
        values: expect.any(Array),
        isDouble: expect.any(Boolean)
      }));
    });

    test('should select token and emit selection', () => {
      // Arrange
      const spy = jest.fn();
      const tokenId = 'token1';
      mockEventBus.on('EVT_TOKEN_SELECTED', spy);
      // Act
      client.selectToken(tokenId);
      // Assert
      expect(spy).toHaveBeenCalledWith({ tokenId });
    });

    test('should send move command when move requested', () => {
      // Arrange
      const sendSpy = jest.fn();
      client.send = sendSpy;
      const steps = 5;
      // Act
      client.move(steps);
      // Assert
      expect(sendSpy).toHaveBeenCalledWith('CMD_MOVE', { steps });
    });

    test('should select artifact and send command', () => {
      // Arrange
      const sendSpy = jest.fn();
      client.send = sendSpy;
      // Act
      client.selectArtifact('Swap', { indices: [0,1] });
      // Assert
      expect(sendSpy).toHaveBeenCalledWith('CMD_SELECT_ARTIFACT', {
        artifactType: 'Swap',
        params: { indices: [0,1] }
      });
    });

    test('should reactivate ultimate when MAG sufficient', () => {
      // Arrange
      client.state.mag = 60;
      const spy = jest.fn();
      client.onUltimateActivated = spy;
      // Act
      client.activateUltimate();
      // Assert
      expect(spy).toHaveBeenCalled();
    });
  });

  // Error paths and edge cases
  describe('error paths & edge cases', () => {
    test('should ignore move if no token selected', () => {
      // Arrange
      client.selectedToken = null;
      const sendSpy = jest.fn();
      client.send = sendSpy;
      // Act
      client.move(3);
      // Assert
      expect(sendSpy).not.toHaveBeenCalled();
    });

    test('should not activate ultimate when MAG < 50', () => {
      // Arrange
      client.state.mag = 30;
      const spy = jest.fn();
      client.onUltimateActivated = spy;
      // Act
      client.activateUltimate();
      // Assert
      expect(spy).not.toHaveBeenCalled();
    });

    test('should handle EVT_EMPTY_TILE_REACHED by showing artifact UI', () => {
      // Arrange
      const showSpy = jest.fn();
      client.showArtifactUI = showSpy;
      const artifacts = ['Swap', 'Change'];
      // Act
      client.onEmptyTileReached(artifacts);
      // Assert
      expect(showSpy).toHaveBeenCalledWith(artifacts);
    });

    test('should queue element updates on EVT_ELEMENT_COLLECTED', () => {
      // Arrange
      const updateSpy = jest.fn();
      client.onElementCollected = updateSpy;
      // Act
      client.onElementCollected({ playerId: 'P1', element: 'Fire', queueLength: 2 });
      // Assert
      expect(updateSpy).toHaveBeenCalledWith(expect.objectContaining({
        element: 'Fire',
        queueLength: 2
      }));
    });

    test('should display combo animation on EVT_COMBO_TRIGGERED', () => {
      // Arrange
      const animSpy = jest.fn();
      client.playComboAnimation = animSpy;
      // Act
      client.onComboTriggered({ type: 'C3', elements: ['Fire','Fire','Fire'], rewards: ['t1'] });
      // Assert
      expect(animSpy).toHaveBeenCalledWith(expect.objectContaining({
        type: 'C3'
      }));
    });

    test('should handle kick event visualization', () => {
      // Arrange
      const kickSpy = jest.fn();
      client.showKickDamage = kickSpy;
      // Act
      client.onKickOccurred({
        attacker: 'tokenP1_1',
        defender: 'tokenP2_2',
        damage: 45,
        defenderNewTile: 5
      });
      // Assert
      expect(kickSpy).toHaveBeenCalledWith(expect.objectContaining({
        damage: 45
      }));
    });

    test('should update HUD on HP change', () => {
      // Arrange
      const hudSpy = jest.fn();
      client.updateHUD = hudSpy;
      // Act
      client.onHealthChanged({ playerId: 'P1', newHp: 950 });
      // Assert
      expect(hudSpy).toHaveBeenCalledWith(expect.objectContaining({
        playerId: 'P1',
        newHp: 950
      }));
    });

    test('should ignore artifact selection if not unlocked', () => {
      // Arrange
      client.unlockedArtifacts = ['Swap']; // 'Change' not unlocked
      const spy = jest.fn();
      client.send = spy;
      // Act
      client.selectArtifact('Change'); // should not send
      // Assert
      expect(spy).not.toHaveBeenCalled();
    });
  });
});
