// src/tests/admin/elemental-hunterTest.java
// Generated by: agent_qc from analysis/REQ-elemental-hunter.md + DESIGN-elemental-hunter.md
// Date: 2026-03-19T12:57:00+07:00
// Hash: req=9D603F615655623FA3625F55D9E096D4, des=8D532B6BD7042617EC45F34922597B23

package elemental.hunter.admin;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Elemental Hunter — Admin Layer Tests (Java / Spring / MockMvc)
 * Scope: REST API for balance config, character/level editors, metrics.
 * These are scaffolding tests — fill in assertions after implementation.
 */

@SpringBootTest
@AutoConfigureMockMvc
class ElementalHunterAdminTest {

  @Autowired
  private MockMvc mockMvc;

  // Helper: sample balance payload
  private String balancePayload = """
    {
      "magCap": 100,
      "maxElementQueue": 8,
      "maxConsecutiveRolls": 3,
      "doubleRollCooldownRounds": 2,
      "ultimateCostExtraRoll": 50
    }
    """;

  @Test
  void should_get_balance_config_for_feature() throws Exception {
    mockMvc.perform(get("/api/balance/elemental-hunter")
            .accept(MediaType.APPLICATION_JSON))
           .andExpect(status().isOk())
           .andExpect(content().contentType(MediaType.APPLICATION_JSON));
    // TODO: assert JSON fields existence and defaults
  }

  @Test
  void should_update_balance_config_successfully() throws Exception {
    mockMvc.perform(put("/api/balance/elemental-hunter")
            .contentType(MediaType.APPLICATION_JSON)
            .content(balancePayload))
           .andExpect(status().isOk())
           .andExpect(jsonPath("$.magCap").value(100))
           .andExpect(jsonPath("$.maxElementQueue").value(8));
    // TODO: persist check via DB or subsequent GET
  }

  @Test
  void should_validate_missing_required_fields_and_return_bad_request() throws Exception {
    String invalid = "{\"magCap\":null}";
    mockMvc.perform(put("/api/balance/elemental-hunter")
            .contentType(MediaType.APPLICATION_JSON)
            .content(invalid))
           .andExpect(status().isBadRequest());
    // TODO: assert error message details
  }

  @Test
  void should_return_404_when_requesting_unknown_feature_balance() throws Exception {
    mockMvc.perform(get("/api/balance/nonexistent-feature"))
           .andExpect(status().isNotFound());
  }

  @Test
  void should_handle_invalid_json_payload_with_500() throws Exception {
    String badJson = "{\"invalid\":\"data\",}";
    mockMvc.perform(post("/api/balance/elemental-hunter/save")
            .contentType(MediaType.APPLICATION_JSON)
            .content(badJson))
           .andExpect(status().isInternalServerError());
  }

  @Test
  void should_get_character_config_list() throws Exception {
    mockMvc.perform(get("/api/characters/elemental-hunter"))
           .andExpect(status().isOk());
    // TODO: assert list includes default Pillow and others
  }

  @Test
  void should_update_character_stats() throws Exception {
    String charPayload = """
      {
        "characterId": "pillow",
        "affinity": "Fire",
        "atk": 30,
        "mag": 10,
        "hp": 1000
      }
      """;
    mockMvc.perform(put("/api/characters/elemental-hunter/pillow")
            .contentType(MediaType.APPLICATION_JSON)
            .content(charPayload))
           .andExpect(status().isOk());
    // TODO: verify update persisted
  }

  @Test
  void should_get_level_config() throws Exception {
    mockMvc.perform(get("/api/levels/elemental-hunter"))
           .andExpect(status().isOk());
  }

  @Test
  void should_update_level_settings() throws Exception {
    String levelPayload = """
      {
        "level": 3,
        "maxRounds": 15,
        "comboTierMax": 3,
        "artifactSlots": 3
      }
      """;
    mockMvc.perform(put("/api/levels/elemental-hunter/3")
            .contentType(MediaType.APPLICATION_JSON)
            .content(levelPayload))
           .andExpect(status().isOk());
  }

  @Test
  void should_get_metrics_dashboard() throws Exception {
    mockMvc.perform(get("/api/metrics/elemental-hunter")
            .param("dateFrom", "2026-03-01")
            .param("dateTo", "2026-03-19"))
           .andExpect(status().isOk())
           .andExpect(jsonPath("$.totalGames").exists());
    // TODO: assert metrics fields: avg KO rate, combo counts, artifact usage
  }
}
