package elemental.hunter.admin;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Admin-side scaffolding tests for Elemental Hunter feature.
 * Generated by: agent_qc from REQ/DESIGN.
 * Date: 2026-03-19 06:17 UTC
 * TODO: Define actual endpoints and fill in assertions.
 */
@SpringBootTest
@AutoConfigureMockMvc
class ElementalHunterAdminTest {

    @Autowired
    private MockMvc mockMvc;

    // Admin endpoints likely: GET /api/admin/balance, POST /api/admin/balance, GET /api/admin/metrics

    @Test
    void should_get_balance_config() throws Exception {
        mockMvc.perform(get("/api/admin/balance/elemental-hunter")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.magCap").exists())
                .andExpect(jsonPath("$.maxElementQueue").exists());
    }

    @Test
    void should_update_balance_config() throws Exception {
        String payload = """
            {
              "magCap": 120,
              "maxElementQueue": 12
            }
            """;

        mockMvc.perform(post("/api/admin/balance/elemental-hunter")
                .contentType(MediaType.APPLICATION_JSON)
                .content(payload))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.updated").value(true));
    }

    @Test
    void should_fail_validation_on_invalid_balance_update() throws Exception {
        String payload = """
            {
              "magCap": -10,
              "maxElementQueue": 12
            }
            """;

        mockMvc.perform(post("/api/admin/balance/elemental-hunter")
                .contentType(MediaType.APPLICATION_JSON)
                .content(payload))
                .andExpect(status().isBadRequest());
    }

    @Test
    void should_get_metrics_dashboard() throws Exception {
        mockMvc.perform(get("/api/admin/metrics/elemental-hunter")
                .param("matchId", "test-match"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.averageGameDuration").exists())
                .andExpect(jsonPath("$.koRate").exists())
                .andExpect(jsonPath("$.comboPerPlayerAvg").exists());
    }

    @Test
    void should_return_404_when_metrics_not_found() throws Exception {
        mockMvc.perform(get("/api/admin/metrics/elemental-hunter")
                .param("matchId", "nonexistent"))
                .andExpect(status().isNotFound());
    }

    @Test
    void should_list_all_balance_configs() throws Exception {
        mockMvc.perform(get("/api/admin/balance")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$").isArray())
                .andExpect(jsonPath("$[?(@.feature == 'elemental-hunter')]").exists());
    }

    // Error path: unauthorized admin access (if security enabled)
    // @Test
    // void should_deny_unauthorized_access() throws Exception {
    //     mockMvc.perform(get("/api/admin/balance/elemental-hunter")
    //             .header("Authorization", "Bearer invalid"))
    //             .andExpect(status().isForbidden());
    // }
}
