// src/tests/admin/elemental-hunterTest.java
// Generated by: agent_qc from analysis REQ/DESIGN (hash changed)
// Layer: Admin (Java/JUnit5 + MockMvc) — testing REST endpoints

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.hamcrest.Matchers.*;

@WebMvcTest(ElementalHunterAdminController.class)
class ElementalHunterAdminTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private BalanceConfigService balanceService;

    @MockBean
    private CharacterConfigService characterService;

    @MockBean
    private MetricsCollector metrics;

    // Use Cases from REQ: Configure Balance, Monitor Metrics

    @Test
    void shouldReturnBalanceConfig() throws Exception {
        // Arrange
        BalanceConfig config = new BalanceConfig();
        config.setMagCap(100);
        config.setMaxElementQueue(6);
        when(balanceService.getConfig()).thenReturn(config);
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/balance")
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.magCap", is(100)))
                .andExpect(jsonPath("$.maxElementQueue", is(6)));
    }

    @Test
    void shouldUpdateBalanceConfig() throws Exception {
        // Arrange
        String json = "{\"magCap\":120,\"maxElementQueue\":8}";
        // Act & Assert
        mockMvc.perform(put("/api/admin/elemental-hunter/balance")
                .content(json)
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.magCap", is(120)))
                .andExpect(jsonPath("$.maxElementQueue", is(8)));
        verify(balanceService).updateConfig(any());
    }

    @Test
    void shouldReturnCharacterConfig() throws Exception {
        // Arrange
        CharacterConfig cc = new CharacterConfig();
        cc.setAffinity("Fire");
        cc.setAtk(30);
        cc.setMag(10);
        cc.setHp(1000);
        when(characterService.getConfig("Pillow")).thenReturn(cc);
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/character/Pillow"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.affinity", is("Fire")))
                .andExpect(jsonPath("$.atk", is(30)));
    }

    @Test
    void shouldUpdateCharacterConfig() throws Exception {
        // Arrange
        String json = "{\"affinity\":\"Ice\",\"atk\":35,\"mag\":12,\"hp\":1100}";
        // Act & Assert
        mockMvc.perform(put("/api/admin/elemental-hunter/character/Pillow")
                .content(json)
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.affinity", is("Ice")))
                .andExpect(jsonPath("$.atk", is(35)));
        verify(characterService).updateConfig(eq("Pillow"), any());
    }

    @Test
    void shouldFetchMetricsDashboard() throws Exception {
        // Arrange
        MetricsDto dto = new MetricsDto();
        dto.setAvgGameDurationSeconds(540);
        dto.setKoRatePercentage(40.0);
        when(metrics.getCurrentStats()).thenReturn(dto);
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/metrics"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.avgGameDurationSeconds", is(540)))
                .andExpect(jsonPath("$.koRatePercentage", is(40.0)));
    }

    @Test
    void shouldReturnEmptySessionListIfNone() throws Exception {
        // Arrange
        when(metrics.getActiveSessions()).thenReturn(emptyList());
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/sessions"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$", empty()));
    }

    // Error paths

    @Test
    void shouldReturn400WhenUpdatingBalanceWithInvalidValues() throws Exception {
        // Arrange: negative magCap
        String json = "{\"magCap\":-10}";
        // Act & Assert
        mockMvc.perform(put("/api/admin/elemental-hunter/balance")
                .content(json)
                .contentType(MediaType.APPLICATION_JSON))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error", containsString("magCap >= 0")));
    }

    @Test
    void shouldReturn404WhenCharacterNotFound() throws Exception {
        // Arrange
        when(characterService.getConfig("Unknown")).thenThrow(new ResourceNotFoundException());
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/character/Unknown"))
                .andExpect(status().isNotFound());
    }

    @Test
    void shouldHandleServiceExceptionDuringMetricsFetch() throws Exception {
        // Arrange
        when(metrics.getCurrentStats()).thenThrow(new IllegalStateException("DB down"));
        // Act & Assert
        mockMvc.perform(get("/api/admin/elemental-hunter/metrics"))
                .andExpect(status().isInternalServerError());
    }
}

// Minimal stubs to compile (these would come from actual codebase)
class BalanceConfig {
    private int magCap;
    private int maxElementQueue;
    // getters/setters
    public int getMagCap() { return magCap; }
    public void setMagCap(int magCap) { this.magCap = magCap; }
    public int getMaxElementQueue() { return maxElementQueue; }
    public void setMaxElementQueue(int maxElementQueue) { this.maxElementQueue = maxElementQueue; }
}
class CharacterConfig {
    private String affinity;
    private int atk;
    private int mag;
    private int hp;
    // getters/setters
    public String getAffinity() { return affinity; }
    public void setAffinity(String affinity) { this.affinity = affinity; }
    public int getAtk() { return atk; }
    public void setAtk(int atk) { this.atk = atk; }
    public int getMag() { return mag; }
    public void setMag(int mag) { this.mag = mag; }
    public int getHp() { return hp; }
    public void setHp(int hp) { this.hp = hp; }
}
class MetricsDto {
    private int avgGameDurationSeconds;
    private double koRatePercentage;
    // getters/setters
    public int getAvgGameDurationSeconds() { return avgGameDurationSeconds; }
    public void setAvgGameDurationSeconds(int avgGameDurationSeconds) { this.avgGameDurationSeconds = avgGameDurationSeconds; }
    public double getKoRatePercentage() { return koRatePercentage; }
    public void setKoRatePercentage(double koRatePercentage) { this.koRatePercentage = koRatePercentage; }
}
interface BalanceConfigService { BalanceConfig getConfig(); void updateConfig(BalanceConfig config); }
interface CharacterConfigService { CharacterConfig getConfig(String name); void updateConfig(String name, CharacterConfig config); }
interface MetricsCollector { MetricsDto getCurrentStats(); List<String> getActiveSessions(); }
class ElementalHunterAdminController {
    // stub for compilation
}
class ResourceNotFoundException extends RuntimeException {}
