// Elemental Hunter - Type Definitions
// Auto-generated by agent_dev_client (Pixel) — 2026-03-19

// ==================== Core Enums ====================

export enum ElementType {
  Fire = 'Fire',
  Ice = 'Ice',
  Grass = 'Grass',
  Rock = 'Rock'
}

export enum TileType {
  Elemental = 'elemental',
  Empty = 'empty',
  SafeZone = 'safe_zone',
  Start = 'start'
}

export enum ArtifactType {
  Swap = 'Swap',
  Change = 'Change',
  Charge = 'Charge'
}

export enum ComboType {
  C3 = 'C3',
  C4 = 'C4'
}

export enum PlayerId {
  P1 = 'P1',
  P2 = 'P2'
}

// ==================== Game State Interfaces ====================

export interface TileState {
  tileId: number;
  tileType: TileType;
  baseElement: ElementType | null;
  currentElement: ElementType | null;
}

export interface TokenState {
  tokenId: string;
  owner: PlayerId;
  tileId: number;
  atk: number;
  frozenRounds: number;
}

export interface PlayerState {
  playerId: PlayerId;
  hp: number;
  mag: number;
  magCap: number;
  elementQueue: ElementType[];
  elementAffinity: ElementType;
  comboCount: number;
  comboTier: 1 | 2 | 3;
  tileGainMultiplier: 1 | 2;
  doubleRollCooldown: number;
  consecutiveRollsThisTurn: number;
  ultimateExtraRolls: number;
  emptyTileVisits: number;
  kickCount: number;
  finishedHorseCount: number;
}

export interface GameState {
  matchId: string;
  phase: 'lobby' | 'playing' | 'ended';
  level: 1 | 2 | 3;
  currentTurn: PlayerId;
  currentRound: number;
  maxRounds: number;
  players: Record<PlayerId, PlayerState>;
  tokens: TokenState[];
  board: TileState[];
  winner: PlayerId | null;
  endReason: 'ko' | 'round_limit' | null;
  matchStartTime: number;
  matchEndTime: number | null;
}

// ==================== Event Payloads (Server → Client) ====================

export interface EventPayloads {
  // Game lifecycle
  'game.start': GameStartEvent;
  'game.over': GameOverEvent;
  'turn.end': TurnEndEvent;

  // Dice
  'dice.result': DiceResultEvent;

  // Token movement
  'token.moved': TokenMovedEvent;
  'token.selected': TokenSelectedEvent;

  // Elements & Combo
  'element.collected': ElementCollectedEvent;
  'combo.triggered': ComboTriggeredEvent;

  // Combat
  'kick.occurred': KickOccurredEvent;
  'goal.reached': GoalReachedEvent;

  // Artifacts
  'empty.tile.reached': EmptyTileReachedEvent;
  'artifact.used': ArtifactUsedEvent;
}

// Individual event interfaces
export interface GameStartEvent {
  level: number;
  character: CharacterConfig;
  tokenPositions: Record<string, number>;
  initialElements: Record<string, ElementType[]>;
}

export interface GameOverEvent {
  winner: PlayerId;
  reason: 'ko' | 'round_limit';
  finalHp: Record<PlayerId, number>;
}

export interface TurnEndEvent {
  nextPlayer: PlayerId;
  currentRound: number;
}

export interface DiceResultEvent {
  values: [number, number];
  isPowerRoll: boolean;
  hitTarget: boolean;
  isDouble: boolean;
  doubleRollCooldown: number;
}

export interface TokenMovedEvent {
  tokenId: string;
  path: number[];
  landedTile: number;
}

export interface TokenSelectedEvent {
  tokenId: string;
  playerId: PlayerId;
}

export interface ElementCollectedEvent {
  playerId: PlayerId;
  element: ElementType;
  tileId: number;
  affinityBonus: boolean;
  queueState: ElementType[];
}

export interface ComboTriggeredEvent {
  playerId: PlayerId;
  type: ComboType;
  elements: ElementType[];
  rewards: ComboReward[];
  cascade: boolean;
}

export interface KickOccurredEvent {
  attacker: TokenState;
  defender: TokenState;
  damage: number;
  defenderNewTile: number;
}

export interface GoalReachedEvent {
  tokenId: string;
  playerId: PlayerId;
  chosenElement: ElementType;
  attackDamage: number;
  defenderHpAfterAttack: number;
}

export interface EmptyTileReachedEvent {
  playerId: PlayerId;
  artifactsAvailable: ArtifactType[];
}

export interface ArtifactUsedEvent {
  playerId: PlayerId;
  artifactType: ArtifactType;
  params?: ArtifactParams;
  queueState: ElementType[];
}

export interface ComboReward {
  tier: 1 | 2 | 3;
  type: 'power_surge' | 'double_harvest' | 'absolute_might';
  applied: boolean;
}

export interface ArtifactParams {
  position?: number;          // Swap: indices
  targetIndex?: number;       // Change: which element in queue to change
  targetElement?: ElementType; // Change: what to change to
}

// ==================== Client → Server Commands ====================

export interface CommandPayloads {
  rollDice: RollDiceCommand;
  selectToken: SelectTokenCommand;
  moveToken: MoveTokenCommand;
  selectArtifact: SelectArtifactCommand;
  selectGoalElement: SelectGoalElementCommand;
  activateUltimate: ActivateUltimateCommand;
  // Power Roll includes optional target range
}

export interface RollDiceCommand {
  powerRollTarget?: [number, number]; // [min, max] inclusive
}

export interface SelectTokenCommand {
  tokenId: string;
}

export interface MoveTokenCommand {
  tokenId: string;
  steps: number;
}

export interface SelectArtifactCommand {
  artifactType: ArtifactType;
  params?: ArtifactParams;
}

export interface SelectGoalElementCommand {
  element: ElementType;
}

export interface ActivateUltimateCommand {
  // No payload needed
}

// ==================== Configuration & Character ====================

export interface CharacterConfig {
  affinity: ElementType;
  atk: number;
  mag: number;
  hp: number;
  ultimateType: string;
  ultimateCost: number;
}

export interface LevelConfig {
  maxRounds: number;
  comboTierMax: 1 | 2 | 3;
  artifactSlots: number;
}

export interface BalanceConfig {
  maxConsecutiveRolls: number;
  doubleRollCooldownRounds: number;
  comboT1AtkBonus: number;
  comboT3AtkMultiplier: number;
  ultimateCostExtraRoll: number;
  powerRollAccuracy: number;
  tileRewardAtk: number;
  tileRewardMag: number;
  tokenCount: number;
  magCap: number;
  maxElementQueue: number;
}

// ==================== Artifact & UI ====================

export interface ArtifactUnlockInfo {
  type: ArtifactType;
  unlocked: boolean;
  unlockCondition: number; // emptyTileVisits needed
}

export interface HudState {
  playerId: PlayerId;
  hp: number;
  maxHp: number;
  mag: number;
  magCap: number;
  elementAffinity: ElementType;
  comboCount: number;
  consecutiveRolls: number;
  maxConsecutiveRolls: number;
  doubleRollCooldown: number;
  emptyTileVisits: number;
  artifacts: ArtifactUnlockInfo[];
}
